// CyberSkill design tokens — generated from tokens/*.css (v1.0.0). Do not edit by hand.
export const tokens = {
  "$meta": {
    "system": "CyberSkill Design System",
    "version": "1.0.0",
    "generated": "2026-07-23",
    "note": "Generated from tokens/*.css. Root grouped by category; theme/element scopes carry overrides only. Regenerate after any token change (see docs/conventions.md)."
  },
  "root": {
    "color": {
      "--cs-color-brand-umber": "#45210E",
      "--cs-color-brand-ochre": "#F4BA17",
      "--cs-color-surface-page": "#FFFDF8",
      "--cs-color-surface-panel": "#FFFFFF",
      "--cs-color-surface-raised": "#FBF4E9",
      "--cs-color-text-primary": "#45210E",
      "--cs-color-text-inverse": "#FFFFFF",
      "--cs-color-text-accent": "#6E3B0E",
      "--cs-color-text-muted": "#6E5A4C",
      "--cs-color-semantic-success": "#166534",
      "--cs-color-semantic-danger": "#B42318",
      "--cs-color-semantic-warning": "#92400E",
      "--cs-color-semantic-info": "#1D4ED8",
      "--cs-color-accent-ochre": "#F4BA17",
      "--cs-color-border-default": "#E7D9C6",
      "--cs-color-link": "#6E3B0E",
      "--cs-color-link-hover": "#45210E"
    },
    "component": {
      "--cs-component-button-primary-bg": "#45210E",
      "--cs-component-button-primary-fg": "#FFFFFF",
      "--cs-component-button-gap": "8px",
      "--cs-component-button-radius": "8px",
      "--cs-component-button-xs-paddingY": "4px",
      "--cs-component-button-xs-paddingX": "10px",
      "--cs-component-button-xs-minHeight": "28px",
      "--cs-component-button-xs-minWidth": "28px",
      "--cs-component-button-xs-minHeight-coarse": "36px",
      "--cs-component-button-sm-paddingY": "8px",
      "--cs-component-button-sm-paddingX": "14px",
      "--cs-component-button-sm-minHeight": "36px",
      "--cs-component-button-sm-minHeight-coarse": "40px",
      "--cs-component-button-md-paddingY": "12px",
      "--cs-component-button-md-paddingX": "20px",
      "--cs-component-button-md-minHeight": "44px",
      "--cs-component-button-md-minHeight-coarse": "44px",
      "--cs-component-button-lg-paddingY": "16px",
      "--cs-component-button-lg-paddingX": "28px",
      "--cs-component-button-lg-minHeight": "52px",
      "--cs-component-textfield-border-default": "#BFA58F",
      "--cs-component-textfield-paddingY": "10px",
      "--cs-component-textfield-paddingX": "12px",
      "--cs-component-textfield-minHeight": "44px"
    },
    "accent": {
      "--cs-accent": "#F4BA17",
      "--cs-accent-strong": "#A47D17",
      "--cs-accent-bright": "#F4BA17",
      "--cs-accent-on": "#45210E",
      "--cs-accent-tint": "#FBF4E9",
      "--cs-accent-ink": "#45210E",
      "--cs-accent-glow": "rgba(244, 186, 23, 0.48)",
      "--cs-accent-grad-a": "#F4BA17",
      "--cs-accent-grad-b": "#FDAE90"
    },
    "depth": {
      "--cs-depth-bg": "0",
      "--cs-depth-section": "5",
      "--cs-depth-card": "10",
      "--cs-depth-nav": "50",
      "--cs-depth-modal": "100",
      "--cs-depth-toast": "200"
    },
    "glass": {
      "--cs-glass-whisper-blur": "8px",
      "--cs-glass-whisper-saturate": "110%",
      "--cs-glass-whisper-opacity": "60%",
      "--cs-glass-light-blur": "12px",
      "--cs-glass-light-saturate": "130%",
      "--cs-glass-light-opacity": "70%",
      "--cs-glass-standard-blur": "16px",
      "--cs-glass-standard-saturate": "150%",
      "--cs-glass-standard-opacity": "80%",
      "--cs-glass-heavy-blur": "24px",
      "--cs-glass-heavy-saturate": "180%",
      "--cs-glass-heavy-opacity": "90%"
    },
    "shadow": {
      "--cs-shadow-xs": "0 1px 2px rgba(69, 33, 14, 0.06)",
      "--cs-shadow-sm": "0 1px 3px rgba(69, 33, 14, 0.04), 0 8px 24px rgba(69, 33, 14, 0.06)",
      "--cs-shadow-md": "0 12px 30px rgba(31, 19, 11, 0.18)",
      "--cs-shadow-lg": "0 20px 60px rgba(69, 33, 14, 0.18)",
      "--cs-shadow-xl": "0 24px 80px rgba(31, 19, 11, 0.26)"
    },
    "duration": {
      "--cs-duration-instant": "80ms",
      "--cs-duration-fast": "120ms",
      "--cs-duration-base": "200ms",
      "--cs-duration-slow": "320ms"
    },
    "ease": {
      "--cs-ease-standard": "cubic-bezier(0.2, 0, 0, 1)",
      "--cs-ease-entrance": "cubic-bezier(0, 0, 0, 1)",
      "--cs-ease-exit": "cubic-bezier(0.4, 0, 1, 1)",
      "--cs-ease-emphasized": "cubic-bezier(0.2, 0, 0, 1)"
    },
    "space": {
      "--cs-space-0": "0px",
      "--cs-space-1": "4px",
      "--cs-space-2": "8px",
      "--cs-space-3": "12px",
      "--cs-space-4": "16px",
      "--cs-space-5": "20px",
      "--cs-space-6": "24px",
      "--cs-space-8": "32px",
      "--cs-space-10": "40px",
      "--cs-space-12": "48px",
      "--cs-space-16": "64px",
      "--cs-space-20": "80px",
      "--cs-space-24": "96px"
    },
    "radius": {
      "--cs-radius-sm": "4px",
      "--cs-radius-md": "8px",
      "--cs-radius-lg": "14px",
      "--cs-radius-full": "999px"
    },
    "breakpoint": {
      "--cs-breakpoint-xs": "0px",
      "--cs-breakpoint-sm": "640px",
      "--cs-breakpoint-md": "768px",
      "--cs-breakpoint-lg": "1024px",
      "--cs-breakpoint-xl": "1280px",
      "--cs-breakpoint-2xl": "1536px"
    },
    "container": {
      "--cs-container-max": "1320px"
    },
    "font": {
      "--cs-font-family-ui": "'Be Vietnam Pro', ui-sans-serif, system-ui, sans-serif",
      "--cs-font-family-display": "'Space Grotesk', 'Be Vietnam Pro', ui-sans-serif, system-ui, sans-serif",
      "--cs-font-family-mono": "'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
      "--cs-font-weight-regular": "400",
      "--cs-font-weight-medium": "500",
      "--cs-font-weight-semibold": "600",
      "--cs-font-weight-bold": "700",
      "--cs-font-weight-extrabold": "800",
      "--cs-font-lineHeight-body": "1.5",
      "--cs-font-lineHeight-heading": "1.35",
      "--cs-font-lineHeight-tight": "1.15",
      "--cs-font-size-xs": "0.75rem",
      "--cs-font-size-sm": "0.875rem",
      "--cs-font-size-base": "1rem",
      "--cs-font-size-md": "1.125rem",
      "--cs-font-size-lg": "1.25rem",
      "--cs-font-size-xl": "1.5rem",
      "--cs-font-size-2xl": "1.875rem",
      "--cs-font-size-3xl": "2.25rem",
      "--cs-font-size-4xl": "3rem",
      "--cs-font-size-5xl": "3.75rem"
    },
    "text": {
      "--cs-text-display": "var(--cs-font-size-5xl)",
      "--cs-text-h1": "var(--cs-font-size-3xl)",
      "--cs-text-h2": "var(--cs-font-size-2xl)",
      "--cs-text-h3": "var(--cs-font-size-xl)",
      "--cs-text-h4": "var(--cs-font-size-lg)",
      "--cs-text-body-lg": "var(--cs-font-size-md)",
      "--cs-text-body": "var(--cs-font-size-base)",
      "--cs-text-secondary": "var(--cs-font-size-sm)",
      "--cs-text-caption": "var(--cs-font-size-xs)",
      "--cs-text-eyebrow": "var(--cs-font-size-xs)"
    },
    "letter": {
      "--cs-letter-spacing-tight": "-0.01em",
      "--cs-letter-spacing-normal": "0",
      "--cs-letter-spacing-caps": "0.08em"
    },
    "heading": {
      "--cs-heading-family": "var(--cs-font-family-ui)",
      "--cs-heading-weight-strong": "var(--cs-font-weight-extrabold)",
      "--cs-heading-weight": "var(--cs-font-weight-bold)",
      "--cs-heading-tracking": "var(--cs-letter-spacing-tight)"
    },
    "icon": {
      "--cs-icon-sm": "16px",
      "--cs-icon-md": "20px",
      "--cs-icon-lg": "24px"
    }
  },
  "themes": {
    "dark": {
      "--cs-color-surface-page": "#1a1108",
      "--cs-color-surface-panel": "#221710",
      "--cs-color-surface-raised": "#2b1e14",
      "--cs-color-text-primary": "#f5ead9",
      "--cs-color-text-inverse": "#1a1108",
      "--cs-color-text-accent": "#f4ba17",
      "--cs-color-text-muted": "#c9b7a3",
      "--cs-color-semantic-success": "#4ADE80",
      "--cs-color-semantic-danger": "#F87171",
      "--cs-color-semantic-warning": "#FBBF24",
      "--cs-color-semantic-info": "#7CB2FB",
      "--cs-color-border-default": "#4a3a2c",
      "--cs-color-link": "#f4ba17",
      "--cs-color-link-hover": "#f5ead9",
      "--cs-component-button-primary-bg": "#f4ba17",
      "--cs-component-button-primary-fg": "#1a1108",
      "--cs-component-textfield-border-default": "#5a4636",
      "--cs-shadow-xs": "0 1px 2px rgba(0, 0, 0, 0.40)",
      "--cs-shadow-sm": "0 1px 3px rgba(0, 0, 0, 0.34), 0 8px 24px rgba(0, 0, 0, 0.42)",
      "--cs-shadow-md": "0 12px 30px rgba(0, 0, 0, 0.50)",
      "--cs-shadow-lg": "0 20px 60px rgba(0, 0, 0, 0.55)",
      "--cs-shadow-xl": "0 24px 80px rgba(0, 0, 0, 0.62)"
    },
    "system": {
      "--cs-color-surface-page": "#1a1108",
      "--cs-color-surface-panel": "#221710",
      "--cs-color-surface-raised": "#2b1e14",
      "--cs-color-text-primary": "#f5ead9",
      "--cs-color-text-inverse": "#1a1108",
      "--cs-color-text-accent": "#f4ba17",
      "--cs-color-text-muted": "#c9b7a3",
      "--cs-color-semantic-success": "#4ADE80",
      "--cs-color-semantic-danger": "#F87171",
      "--cs-color-semantic-warning": "#FBBF24",
      "--cs-color-semantic-info": "#7CB2FB",
      "--cs-color-border-default": "#4a3a2c",
      "--cs-color-link": "#f4ba17",
      "--cs-color-link-hover": "#f5ead9",
      "--cs-component-button-primary-bg": "#f4ba17",
      "--cs-component-button-primary-fg": "#1a1108",
      "--cs-component-textfield-border-default": "#5a4636",
      "--cs-shadow-xs": "0 1px 2px rgba(0, 0, 0, 0.40)",
      "--cs-shadow-sm": "0 1px 3px rgba(0, 0, 0, 0.34), 0 8px 24px rgba(0, 0, 0, 0.42)",
      "--cs-shadow-md": "0 12px 30px rgba(0, 0, 0, 0.50)",
      "--cs-shadow-lg": "0 20px 60px rgba(0, 0, 0, 0.55)",
      "--cs-shadow-xl": "0 24px 80px rgba(0, 0, 0, 0.62)"
    }
  },
  "elements": {
    "tho.sand": {
      "--cs-accent": "#F8E9C0",
      "--cs-accent-strong": "#90825E",
      "--cs-accent-bright": "#F6EBCC",
      "--cs-accent-on": "#292414",
      "--cs-accent-tint": "#FBF7EA",
      "--cs-accent-ink": "#292414",
      "--cs-accent-glow": "rgba(248, 233, 192, 0.48)",
      "--cs-accent-grad-a": "#F8E9C0",
      "--cs-accent-grad-b": "#FDAE90",
      "--cs-color-text-accent": "#90825E",
      "--cs-color-link": "#90825E"
    },
    "tho": {
      "--cs-accent": "#F4BA17",
      "--cs-accent-strong": "#A47D17",
      "--cs-accent-bright": "#F4BA17",
      "--cs-accent-on": "#45210E",
      "--cs-accent-tint": "#FBF4E9",
      "--cs-accent-ink": "#45210E",
      "--cs-accent-glow": "rgba(244, 186, 23, 0.48)",
      "--cs-accent-grad-a": "#F4BA17",
      "--cs-accent-grad-b": "#FDAE90"
    },
    "tho.clay": {
      "--cs-accent": "#513801",
      "--cs-accent-strong": "#201300",
      "--cs-accent-bright": "#DEC7A2",
      "--cs-accent-on": "#2D220E",
      "--cs-accent-tint": "#FFF6E7",
      "--cs-accent-ink": "#2D220E",
      "--cs-accent-glow": "rgba(81, 56, 1, 0.48)",
      "--cs-accent-grad-a": "#513801",
      "--cs-accent-grad-b": "#FDAE90",
      "--cs-color-text-accent": "#201300",
      "--cs-color-link": "#201300"
    },
    "hoa.plasma": {
      "--cs-accent": "#FFE1D8",
      "--cs-accent-strong": "#967C75",
      "--cs-accent-bright": "#FCE6DF",
      "--cs-accent-on": "#2C211E",
      "--cs-accent-tint": "#FEF4F2",
      "--cs-accent-ink": "#2C211E",
      "--cs-accent-glow": "rgba(255, 225, 216, 0.48)",
      "--cs-accent-grad-a": "#FFE1D8",
      "--cs-accent-grad-b": "#F4BA17",
      "--cs-color-text-accent": "#967C75",
      "--cs-color-link": "#967C75"
    },
    "hoa": {
      "--cs-accent": "#FDAE90",
      "--cs-accent-strong": "#B56F54",
      "--cs-accent-bright": "#FFD3C2",
      "--cs-accent-on": "#381B0F",
      "--cs-accent-tint": "#FFF4F0",
      "--cs-accent-ink": "#381B0F",
      "--cs-accent-glow": "rgba(253, 174, 144, 0.48)",
      "--cs-accent-grad-a": "#FDAE90",
      "--cs-accent-grad-b": "#F4BA17",
      "--cs-color-text-accent": "#B56F54",
      "--cs-color-link": "#B56F54"
    },
    "hoa.lava": {
      "--cs-accent": "#632B03",
      "--cs-accent-strong": "#290D00",
      "--cs-accent-bright": "#F1BEA2",
      "--cs-accent-on": "#361D0E",
      "--cs-accent-tint": "#FFF4EE",
      "--cs-accent-ink": "#361D0E",
      "--cs-accent-glow": "rgba(99, 43, 3, 0.48)",
      "--cs-accent-grad-a": "#632B03",
      "--cs-accent-grad-b": "#F4BA17",
      "--cs-color-text-accent": "#290D00",
      "--cs-color-link": "#290D00"
    },
    "thuy.mist": {
      "--cs-accent": "#C0F5FC",
      "--cs-accent-strong": "#5A8A90",
      "--cs-accent-bright": "#CDF4F9",
      "--cs-accent-on": "#13282B",
      "--cs-accent-tint": "#EBFAFC",
      "--cs-accent-ink": "#13282B",
      "--cs-accent-glow": "rgba(192, 245, 252, 0.48)",
      "--cs-accent-grad-a": "#C0F5FC",
      "--cs-accent-grad-b": "#A3D768",
      "--cs-color-text-accent": "#5A8A90",
      "--cs-color-link": "#5A8A90"
    },
    "thuy": {
      "--cs-accent": "#2EDBF7",
      "--cs-accent-strong": "#108EA0",
      "--cs-accent-bright": "#99EEFF",
      "--cs-accent-on": "#012A30",
      "--cs-accent-tint": "#E7FBFF",
      "--cs-accent-ink": "#012A30",
      "--cs-accent-glow": "rgba(46, 219, 247, 0.48)",
      "--cs-accent-grad-a": "#2EDBF7",
      "--cs-accent-grad-b": "#A3D768",
      "--cs-color-text-accent": "#108EA0",
      "--cs-color-link": "#108EA0"
    },
    "thuy.ocean": {
      "--cs-accent": "#004554",
      "--cs-accent-strong": "#011A21",
      "--cs-accent-bright": "#A8D3E0",
      "--cs-accent-on": "#10282F",
      "--cs-accent-tint": "#EAFAFF",
      "--cs-accent-ink": "#10282F",
      "--cs-accent-glow": "rgba(0, 69, 84, 0.48)",
      "--cs-accent-grad-a": "#004554",
      "--cs-accent-grad-b": "#A3D768",
      "--cs-color-text-accent": "#011A21",
      "--cs-color-link": "#011A21"
    },
    "moc.bamboo": {
      "--cs-accent": "#E1F1C8",
      "--cs-accent-strong": "#7C8965",
      "--cs-accent-bright": "#E5F1D2",
      "--cs-accent-on": "#212617",
      "--cs-accent-tint": "#F4F9ED",
      "--cs-accent-ink": "#212617",
      "--cs-accent-glow": "rgba(225, 241, 200, 0.48)",
      "--cs-accent-grad-a": "#E1F1C8",
      "--cs-accent-grad-b": "#FDAE90",
      "--cs-color-text-accent": "#7C8965",
      "--cs-color-link": "#7C8965"
    },
    "moc": {
      "--cs-accent": "#A3D768",
      "--cs-accent-strong": "#629122",
      "--cs-accent-bright": "#C5ED9C",
      "--cs-accent-on": "#182A00",
      "--cs-accent-tint": "#EFFCE3",
      "--cs-accent-ink": "#182A00",
      "--cs-accent-glow": "rgba(163, 215, 104, 0.48)",
      "--cs-accent-grad-a": "#A3D768",
      "--cs-accent-grad-b": "#FDAE90",
      "--cs-color-text-accent": "#629122",
      "--cs-color-link": "#629122"
    },
    "moc.forest": {
      "--cs-accent": "#1A4A01",
      "--cs-accent-strong": "#051D00",
      "--cs-accent-bright": "#B0D8A3",
      "--cs-accent-on": "#162A0E",
      "--cs-accent-tint": "#ECFDE7",
      "--cs-accent-ink": "#162A0E",
      "--cs-accent-glow": "rgba(26, 74, 1, 0.48)",
      "--cs-accent-grad-a": "#1A4A01",
      "--cs-accent-grad-b": "#FDAE90",
      "--cs-color-text-accent": "#051D00",
      "--cs-color-link": "#051D00"
    },
    "kim.titanium": {
      "--cs-accent": "#FBE6CB",
      "--cs-accent-strong": "#938068",
      "--cs-accent-bright": "#F8E9D4",
      "--cs-accent-on": "#2A2319",
      "--cs-accent-tint": "#FCF6EE",
      "--cs-accent-ink": "#2A2319",
      "--cs-accent-glow": "rgba(251, 230, 203, 0.48)",
      "--cs-accent-grad-a": "#FBE6CB",
      "--cs-accent-grad-b": "#2EDBF7",
      "--cs-color-text-accent": "#938068",
      "--cs-color-link": "#938068"
    },
    "kim": {
      "--cs-accent": "#EDBB69",
      "--cs-accent-strong": "#A77A2A",
      "--cs-accent-bright": "#FED89D",
      "--cs-accent-on": "#322001",
      "--cs-accent-tint": "#FFF5E6",
      "--cs-accent-ink": "#322001",
      "--cs-accent-glow": "rgba(237, 187, 105, 0.48)",
      "--cs-accent-grad-a": "#EDBB69",
      "--cs-accent-grad-b": "#2EDBF7",
      "--cs-color-text-accent": "#A77A2A",
      "--cs-color-link": "#A77A2A"
    },
    "kim.steel": {
      "--cs-accent": "#4F3904",
      "--cs-accent-strong": "#1F1400",
      "--cs-accent-bright": "#DCC8A4",
      "--cs-accent-on": "#2C220F",
      "--cs-accent-tint": "#FEF6E7",
      "--cs-accent-ink": "#2C220F",
      "--cs-accent-glow": "rgba(79, 57, 4, 0.48)",
      "--cs-accent-grad-a": "#4F3904",
      "--cs-accent-grad-b": "#2EDBF7",
      "--cs-color-text-accent": "#1F1400",
      "--cs-color-link": "#1F1400"
    }
  }
};
export default tokens;
