// CyberSkill design tokens — generated from tokens/*.css (v1.0.0). Do not edit by hand.
export const tokens = {
  "$meta": {
    "system": "CyberSkill Design System",
    "version": "1.0.0",
    "generated": "2026-07-23",
    "note": "Generated from tokens/*.css. Root grouped by category; theme/element scopes carry overrides only. Regenerate after any token change (see docs/conventions.md)."
  },
  "root": {
    "color": {
      "--cs-color-brand-umber": "#45210E",
      "--cs-color-brand-ochre": "#F4BA17",
      "--cs-color-surface-page": "#FFFDF8",
      "--cs-color-surface-panel": "#FFFFFF",
      "--cs-color-surface-raised": "#FBF4E9",
      "--cs-color-text-primary": "#45210E",
      "--cs-color-text-inverse": "#FFFFFF",
      "--cs-color-text-accent": "#6E3B0E",
      "--cs-color-text-muted": "#6E5A4C",
      "--cs-color-semantic-success": "#166534",
      "--cs-color-semantic-danger": "#B42318",
      "--cs-color-semantic-warning": "#92400E",
      "--cs-color-semantic-info": "#1D4ED8",
      "--cs-color-accent-ochre": "#F4BA17",
      "--cs-color-border-default": "#E7D9C6",
      "--cs-color-link": "#6E3B0E",
      "--cs-color-link-hover": "#45210E"
    },
    "component": {
      "--cs-component-button-primary-bg": "#45210E",
      "--cs-component-button-primary-fg": "#FFFFFF",
      "--cs-component-button-gap": "8px",
      "--cs-component-button-radius": "8px",
      "--cs-component-button-xs-paddingY": "4px",
      "--cs-component-button-xs-paddingX": "10px",
      "--cs-component-button-xs-minHeight": "28px",
      "--cs-component-button-xs-minWidth": "28px",
      "--cs-component-button-xs-minHeight-coarse": "36px",
      "--cs-component-button-sm-paddingY": "8px",
      "--cs-component-button-sm-paddingX": "14px",
      "--cs-component-button-sm-minHeight": "36px",
      "--cs-component-button-sm-minHeight-coarse": "40px",
      "--cs-component-button-md-paddingY": "12px",
      "--cs-component-button-md-paddingX": "20px",
      "--cs-component-button-md-minHeight": "44px",
      "--cs-component-button-md-minHeight-coarse": "44px",
      "--cs-component-button-lg-paddingY": "16px",
      "--cs-component-button-lg-paddingX": "28px",
      "--cs-component-button-lg-minHeight": "52px",
      "--cs-component-textfield-border-default": "#BFA58F",
      "--cs-component-textfield-paddingY": "10px",
      "--cs-component-textfield-paddingX": "12px",
      "--cs-component-textfield-minHeight": "44px"
    },
    "accent": {
      "--cs-accent": "#F4BA17",
      "--cs-accent-strong": "#9E770B",
      "--cs-accent-bright": "#F4BA17",
      "--cs-accent-on": "#45210E",
      "--cs-accent-tint": "#FBF4E9",
      "--cs-accent-ink": "#45210E",
      "--cs-accent-glow": "rgba(244, 186, 23, 0.5)",
      "--cs-accent-grad-a": "#F4BA17",
      "--cs-accent-grad-b": "#FFAD8E"
    },
    "depth": {
      "--cs-depth-bg": "0",
      "--cs-depth-section": "5",
      "--cs-depth-card": "10",
      "--cs-depth-nav": "50",
      "--cs-depth-modal": "100",
      "--cs-depth-toast": "200"
    },
    "glass": {
      "--cs-glass-whisper-blur": "8px",
      "--cs-glass-whisper-saturate": "110%",
      "--cs-glass-whisper-opacity": "60%",
      "--cs-glass-light-blur": "12px",
      "--cs-glass-light-saturate": "130%",
      "--cs-glass-light-opacity": "70%",
      "--cs-glass-standard-blur": "16px",
      "--cs-glass-standard-saturate": "150%",
      "--cs-glass-standard-opacity": "80%",
      "--cs-glass-heavy-blur": "24px",
      "--cs-glass-heavy-saturate": "180%",
      "--cs-glass-heavy-opacity": "90%"
    },
    "shadow": {
      "--cs-shadow-xs": "0 1px 2px rgba(69, 33, 14, 0.06)",
      "--cs-shadow-sm": "0 1px 3px rgba(69, 33, 14, 0.04), 0 8px 24px rgba(69, 33, 14, 0.06)",
      "--cs-shadow-md": "0 12px 30px rgba(31, 19, 11, 0.18)",
      "--cs-shadow-lg": "0 20px 60px rgba(69, 33, 14, 0.18)",
      "--cs-shadow-xl": "0 24px 80px rgba(31, 19, 11, 0.26)"
    },
    "duration": {
      "--cs-duration-instant": "80ms",
      "--cs-duration-fast": "120ms",
      "--cs-duration-base": "200ms",
      "--cs-duration-slow": "320ms"
    },
    "ease": {
      "--cs-ease-standard": "cubic-bezier(0.2, 0, 0, 1)",
      "--cs-ease-entrance": "cubic-bezier(0, 0, 0, 1)",
      "--cs-ease-exit": "cubic-bezier(0.4, 0, 1, 1)",
      "--cs-ease-emphasized": "cubic-bezier(0.2, 0, 0, 1)"
    },
    "space": {
      "--cs-space-0": "0px",
      "--cs-space-1": "4px",
      "--cs-space-2": "8px",
      "--cs-space-3": "12px",
      "--cs-space-4": "16px",
      "--cs-space-5": "20px",
      "--cs-space-6": "24px",
      "--cs-space-8": "32px",
      "--cs-space-10": "40px",
      "--cs-space-12": "48px",
      "--cs-space-16": "64px",
      "--cs-space-20": "80px",
      "--cs-space-24": "96px"
    },
    "radius": {
      "--cs-radius-sm": "4px",
      "--cs-radius-md": "8px",
      "--cs-radius-lg": "14px",
      "--cs-radius-full": "999px"
    },
    "breakpoint": {
      "--cs-breakpoint-xs": "0px",
      "--cs-breakpoint-sm": "640px",
      "--cs-breakpoint-md": "768px",
      "--cs-breakpoint-lg": "1024px",
      "--cs-breakpoint-xl": "1280px",
      "--cs-breakpoint-2xl": "1536px"
    },
    "container": {
      "--cs-container-max": "1320px"
    },
    "font": {
      "--cs-font-family-ui": "'Be Vietnam Pro', ui-sans-serif, system-ui, sans-serif",
      "--cs-font-family-display": "'Space Grotesk', 'Be Vietnam Pro', ui-sans-serif, system-ui, sans-serif",
      "--cs-font-family-mono": "'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
      "--cs-font-weight-regular": "400",
      "--cs-font-weight-medium": "500",
      "--cs-font-weight-semibold": "600",
      "--cs-font-weight-bold": "700",
      "--cs-font-weight-extrabold": "800",
      "--cs-font-lineHeight-body": "1.5",
      "--cs-font-lineHeight-heading": "1.35",
      "--cs-font-lineHeight-tight": "1.15",
      "--cs-font-size-xs": "0.75rem",
      "--cs-font-size-sm": "0.875rem",
      "--cs-font-size-base": "1rem",
      "--cs-font-size-md": "1.125rem",
      "--cs-font-size-lg": "1.25rem",
      "--cs-font-size-xl": "1.5rem",
      "--cs-font-size-2xl": "1.875rem",
      "--cs-font-size-3xl": "2.25rem",
      "--cs-font-size-4xl": "3rem",
      "--cs-font-size-5xl": "3.75rem"
    },
    "text": {
      "--cs-text-display": "var(--cs-font-size-5xl)",
      "--cs-text-h1": "var(--cs-font-size-3xl)",
      "--cs-text-h2": "var(--cs-font-size-2xl)",
      "--cs-text-h3": "var(--cs-font-size-xl)",
      "--cs-text-h4": "var(--cs-font-size-lg)",
      "--cs-text-body-lg": "var(--cs-font-size-md)",
      "--cs-text-body": "var(--cs-font-size-base)",
      "--cs-text-secondary": "var(--cs-font-size-sm)",
      "--cs-text-caption": "var(--cs-font-size-xs)",
      "--cs-text-eyebrow": "var(--cs-font-size-xs)"
    },
    "letter": {
      "--cs-letter-spacing-tight": "-0.01em",
      "--cs-letter-spacing-normal": "0",
      "--cs-letter-spacing-caps": "0.08em"
    },
    "heading": {
      "--cs-heading-family": "var(--cs-font-family-ui)",
      "--cs-heading-weight-strong": "var(--cs-font-weight-extrabold)",
      "--cs-heading-weight": "var(--cs-font-weight-bold)",
      "--cs-heading-tracking": "var(--cs-letter-spacing-tight)"
    },
    "icon": {
      "--cs-icon-sm": "16px",
      "--cs-icon-md": "20px",
      "--cs-icon-lg": "24px"
    }
  },
  "themes": {
    "dark": {
      "--cs-color-surface-page": "#1a1108",
      "--cs-color-surface-panel": "#221710",
      "--cs-color-surface-raised": "#2b1e14",
      "--cs-color-text-primary": "#f5ead9",
      "--cs-color-text-inverse": "#1a1108",
      "--cs-color-text-accent": "#f4ba17",
      "--cs-color-text-muted": "#c9b7a3",
      "--cs-color-semantic-success": "#4ADE80",
      "--cs-color-semantic-danger": "#F87171",
      "--cs-color-semantic-warning": "#FBBF24",
      "--cs-color-semantic-info": "#7CB2FB",
      "--cs-color-border-default": "#4a3a2c",
      "--cs-color-link": "#f4ba17",
      "--cs-color-link-hover": "#f5ead9",
      "--cs-component-button-primary-bg": "#f4ba17",
      "--cs-component-button-primary-fg": "#1a1108",
      "--cs-component-textfield-border-default": "#5a4636",
      "--cs-shadow-xs": "0 1px 2px rgba(0, 0, 0, 0.40)",
      "--cs-shadow-sm": "0 1px 3px rgba(0, 0, 0, 0.34), 0 8px 24px rgba(0, 0, 0, 0.42)",
      "--cs-shadow-md": "0 12px 30px rgba(0, 0, 0, 0.50)",
      "--cs-shadow-lg": "0 20px 60px rgba(0, 0, 0, 0.55)",
      "--cs-shadow-xl": "0 24px 80px rgba(0, 0, 0, 0.62)"
    },
    "system": {
      "--cs-color-surface-page": "#1a1108",
      "--cs-color-surface-panel": "#221710",
      "--cs-color-surface-raised": "#2b1e14",
      "--cs-color-text-primary": "#f5ead9",
      "--cs-color-text-inverse": "#1a1108",
      "--cs-color-text-accent": "#f4ba17",
      "--cs-color-text-muted": "#c9b7a3",
      "--cs-color-semantic-success": "#4ADE80",
      "--cs-color-semantic-danger": "#F87171",
      "--cs-color-semantic-warning": "#FBBF24",
      "--cs-color-semantic-info": "#7CB2FB",
      "--cs-color-border-default": "#4a3a2c",
      "--cs-color-link": "#f4ba17",
      "--cs-color-link-hover": "#f5ead9",
      "--cs-component-button-primary-bg": "#f4ba17",
      "--cs-component-button-primary-fg": "#1a1108",
      "--cs-component-textfield-border-default": "#5a4636",
      "--cs-shadow-xs": "0 1px 2px rgba(0, 0, 0, 0.40)",
      "--cs-shadow-sm": "0 1px 3px rgba(0, 0, 0, 0.34), 0 8px 24px rgba(0, 0, 0, 0.42)",
      "--cs-shadow-md": "0 12px 30px rgba(0, 0, 0, 0.50)",
      "--cs-shadow-lg": "0 20px 60px rgba(0, 0, 0, 0.55)",
      "--cs-shadow-xl": "0 24px 80px rgba(0, 0, 0, 0.62)"
    }
  },
  "elements": {
    "tho.sand": {
      "--cs-accent": "#FAECB2",
      "--cs-accent-strong": "#8B7D4A",
      "--cs-accent-bright": "#F7ECC1",
      "--cs-accent-on": "#2E2915",
      "--cs-accent-tint": "#F5F2E6",
      "--cs-accent-ink": "#2E2915",
      "--cs-accent-glow": "rgba(250, 236, 178, 0.5)",
      "--cs-accent-grad-a": "#FAECB2",
      "--cs-accent-grad-b": "#FFAD8E",
      "--cs-color-text-accent": "#8B7D4A",
      "--cs-color-link": "#8B7D4A"
    },
    "tho": {
      "--cs-accent": "#F4BA17",
      "--cs-accent-strong": "#9E770B",
      "--cs-accent-bright": "#F4BA17",
      "--cs-accent-on": "#45210E",
      "--cs-accent-tint": "#FBF4E9",
      "--cs-accent-ink": "#45210E",
      "--cs-accent-glow": "rgba(244, 186, 23, 0.5)",
      "--cs-accent-grad-a": "#F4BA17",
      "--cs-accent-grad-b": "#FFAD8E"
    },
    "tho.clay": {
      "--cs-accent": "#8A6010",
      "--cs-accent-strong": "#4C3201",
      "--cs-accent-bright": "#F6C06B",
      "--cs-accent-on": "#382503",
      "--cs-accent-tint": "#FFEFD8",
      "--cs-accent-ink": "#382503",
      "--cs-accent-glow": "rgba(138, 96, 16, 0.5)",
      "--cs-accent-grad-a": "#8A6010",
      "--cs-accent-grad-b": "#FFAD8E",
      "--cs-color-text-accent": "#4C3201",
      "--cs-color-link": "#4C3201"
    },
    "hoa.plasma": {
      "--cs-accent": "#FFE3E6",
      "--cs-accent-strong": "#B65E6D",
      "--cs-accent-bright": "#FFE3E6",
      "--cs-accent-on": "#3F1D23",
      "--cs-accent-tint": "#FFECEE",
      "--cs-accent-ink": "#3F1D23",
      "--cs-accent-glow": "rgba(255, 227, 230, 0.5)",
      "--cs-accent-grad-a": "#FFE3E6",
      "--cs-accent-grad-b": "#F4BA17",
      "--cs-color-text-accent": "#B65E6D",
      "--cs-color-link": "#B65E6D"
    },
    "hoa": {
      "--cs-accent": "#FFAD8E",
      "--cs-accent-strong": "#C36036",
      "--cs-accent-bright": "#FFCAB5",
      "--cs-accent-on": "#431C0B",
      "--cs-accent-tint": "#FFEEE7",
      "--cs-accent-ink": "#431C0B",
      "--cs-accent-glow": "rgba(255, 173, 142, 0.5)",
      "--cs-accent-grad-a": "#FFAD8E",
      "--cs-accent-grad-b": "#F4BA17",
      "--cs-color-text-accent": "#C36036",
      "--cs-color-link": "#C36036"
    },
    "hoa.lava": {
      "--cs-accent": "#9C5215",
      "--cs-accent-strong": "#572A03",
      "--cs-accent-bright": "#FFB98B",
      "--cs-accent-on": "#421E02",
      "--cs-accent-tint": "#FFEEE4",
      "--cs-accent-ink": "#421E02",
      "--cs-accent-glow": "rgba(156, 82, 21, 0.5)",
      "--cs-accent-grad-a": "#9C5215",
      "--cs-accent-grad-b": "#F4BA17",
      "--cs-color-text-accent": "#572A03",
      "--cs-color-link": "#572A03"
    },
    "thuy.mist": {
      "--cs-accent": "#B4FAFC",
      "--cs-accent-strong": "#468689",
      "--cs-accent-bright": "#C3F7F8",
      "--cs-accent-on": "#142E2E",
      "--cs-accent-tint": "#E7F5F5",
      "--cs-accent-ink": "#142E2E",
      "--cs-accent-glow": "rgba(180, 250, 252, 0.5)",
      "--cs-accent-grad-a": "#B4FAFC",
      "--cs-accent-grad-b": "#ADD386",
      "--cs-color-text-accent": "#468689",
      "--cs-color-link": "#468689"
    },
    "thuy": {
      "--cs-accent": "#87D2E1",
      "--cs-accent-strong": "#408693",
      "--cs-accent-bright": "#ACE2EE",
      "--cs-accent-on": "#122D33",
      "--cs-accent-tint": "#E6F5F8",
      "--cs-accent-ink": "#122D33",
      "--cs-accent-glow": "rgba(135, 210, 225, 0.5)",
      "--cs-accent-grad-a": "#87D2E1",
      "--cs-accent-grad-b": "#ADD386",
      "--cs-color-text-accent": "#408693",
      "--cs-color-link": "#408693"
    },
    "thuy.ocean": {
      "--cs-accent": "#037492",
      "--cs-accent-strong": "#063E4F",
      "--cs-accent-bright": "#8AD7F4",
      "--cs-accent-on": "#012E3C",
      "--cs-accent-tint": "#E1F6FF",
      "--cs-accent-ink": "#012E3C",
      "--cs-accent-glow": "rgba(3, 116, 146, 0.5)",
      "--cs-accent-grad-a": "#037492",
      "--cs-accent-grad-b": "#ADD386",
      "--cs-color-text-accent": "#063E4F",
      "--cs-color-link": "#063E4F"
    },
    "moc.bamboo": {
      "--cs-accent": "#EAF3AD",
      "--cs-accent-strong": "#7C8345",
      "--cs-accent-bright": "#EAF1BD",
      "--cs-accent-on": "#292B13",
      "--cs-accent-tint": "#F1F4E5",
      "--cs-accent-ink": "#292B13",
      "--cs-accent-glow": "rgba(234, 243, 173, 0.5)",
      "--cs-accent-grad-a": "#EAF3AD",
      "--cs-accent-grad-b": "#FFAD8E",
      "--cs-color-text-accent": "#7C8345",
      "--cs-color-link": "#7C8345"
    },
    "moc": {
      "--cs-accent": "#ADD386",
      "--cs-accent-strong": "#668741",
      "--cs-accent-bright": "#C6E3AA",
      "--cs-accent-on": "#212E12",
      "--cs-accent-tint": "#ECF5E5",
      "--cs-accent-ink": "#212E12",
      "--cs-accent-glow": "rgba(173, 211, 134, 0.5)",
      "--cs-accent-grad-a": "#ADD386",
      "--cs-accent-grad-b": "#FFAD8E",
      "--cs-color-text-accent": "#668741",
      "--cs-color-link": "#668741"
    },
    "moc.forest": {
      "--cs-accent": "#2B7C2F",
      "--cs-accent-strong": "#09450E",
      "--cs-accent-bright": "#A1DDA0",
      "--cs-accent-on": "#133114",
      "--cs-accent-tint": "#E6F8E5",
      "--cs-accent-ink": "#133114",
      "--cs-accent-glow": "rgba(43, 124, 47, 0.5)",
      "--cs-accent-grad-a": "#2B7C2F",
      "--cs-accent-grad-b": "#FFAD8E",
      "--cs-color-text-accent": "#09450E",
      "--cs-color-link": "#09450E"
    },
    "kim.titanium": {
      "--cs-accent": "#FFE6D3",
      "--cs-accent-strong": "#8F7867",
      "--cs-accent-bright": "#FBE7D8",
      "--cs-accent-on": "#302720",
      "--cs-accent-tint": "#F6F0EC",
      "--cs-accent-ink": "#302720",
      "--cs-accent-glow": "rgba(255, 230, 211, 0.5)",
      "--cs-accent-grad-a": "#FFE6D3",
      "--cs-accent-grad-b": "#87D2E1",
      "--cs-color-text-accent": "#8F7867",
      "--cs-color-link": "#8F7867"
    },
    "kim": {
      "--cs-accent": "#D1C2A8",
      "--cs-accent-strong": "#897B65",
      "--cs-accent-bright": "#E1D6C2",
      "--cs-accent-on": "#2D281F",
      "--cs-accent-tint": "#F5F1EB",
      "--cs-accent-ink": "#2D281F",
      "--cs-accent-glow": "rgba(209, 194, 168, 0.5)",
      "--cs-accent-grad-a": "#D1C2A8",
      "--cs-accent-grad-b": "#87D2E1",
      "--cs-color-text-accent": "#897B65",
      "--cs-color-link": "#897B65"
    },
    "kim.steel": {
      "--cs-accent": "#447273",
      "--cs-accent-strong": "#134040",
      "--cs-accent-bright": "#AFD3D3",
      "--cs-accent-on": "#1B2C2D",
      "--cs-accent-tint": "#EAF4F4",
      "--cs-accent-ink": "#1B2C2D",
      "--cs-accent-glow": "rgba(68, 114, 115, 0.5)",
      "--cs-accent-grad-a": "#447273",
      "--cs-accent-grad-b": "#87D2E1",
      "--cs-color-text-accent": "#134040",
      "--cs-color-link": "#134040"
    }
  }
};
export default tokens;
