/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-template-stories.mjs — do not hand-edit. */
import React from 'react';
import { IframeSurface } from '../../Maintainer/IframeSurface.jsx';

export default {
  title: 'Templates/Board',
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Design Component starting points from _ds_manifest.json (Atomic View grouping). Portable HTML under templates/.',
      },
    },
  },
};

export const BodMemo = {
  name: `Executive memo`,
  render: () => (
    <IframeSurface src="/templates/bod-memo/BodMemo.dc.html" title={`Board · Executive memo`} />
  ),
};

export const BodInvestorUpdate = {
  name: `Investor update email`,
  render: () => (
    <IframeSurface src="/templates/bod-investor-update/BodInvestorUpdate.dc.html" title={`Board · Investor update email`} />
  ),
};

export const BodDeck = {
  name: `Meeting deck`,
  render: () => (
    <IframeSurface src="/templates/bod-deck/BodDeck.dc.html" title={`Board · Meeting deck`} />
  ),
};

export const BodMinutes = {
  name: `Meeting minutes`,
  render: () => (
    <IframeSurface src="/templates/bod-minutes/BodMinutes.dc.html" title={`Board · Meeting minutes`} />
  ),
};

export const BodReport = {
  name: `Quarterly report`,
  render: () => (
    <IframeSurface src="/templates/bod-report/BodReport.dc.html" title={`Board · Quarterly report`} />
  ),
};

export const BodResolution = {
  name: `Resolution`,
  render: () => (
    <IframeSurface src="/templates/bod-resolution/BodResolution.dc.html" title={`Board · Resolution`} />
  ),
};
