/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-template-stories.mjs — do not hand-edit. */
import React from 'react';
import { IframeSurface } from '../../Maintainer/IframeSurface.jsx';

export default {
  title: 'Templates/Culture',
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Design Component starting points from _ds_manifest.json (Atomic View grouping). Portable HTML under templates/.',
      },
    },
  },
};

export const CultureEventInvite = {
  name: `Event invite`,
  render: () => (
    <IframeSurface src="/templates/culture-event-invite/CultureEventInvite.dc.html" title={`Culture · Event invite`} />
  ),
};
