/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-template-stories.mjs — do not hand-edit. */
import React from 'react';
import { IframeSurface } from '../../Maintainer/IframeSurface.jsx';

export default {
  title: 'Templates/Delivery',
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Design Component starting points from _ds_manifest.json (Atomic View grouping). Portable HTML under templates/.',
      },
    },
  },
};

export const DeliveryChangeNote = {
  name: `Change note`,
  render: () => (
    <IframeSurface src="/templates/delivery-change-note/DeliveryChangeNote.dc.html" title={`Delivery · Change note`} />
  ),
};

export const DeliveryKickoff = {
  name: `Kickoff doc`,
  render: () => (
    <IframeSurface src="/templates/delivery-kickoff/DeliveryKickoff.dc.html" title={`Delivery · Kickoff doc`} />
  ),
};

export const DeliveryQbrDeck = {
  name: `QBR deck`,
  render: () => (
    <IframeSurface src="/templates/delivery-qbr-deck/DeliveryQbrDeck.dc.html" title={`Delivery · QBR deck`} />
  ),
};

export const DeliveryRunbook = {
  name: `Runbook / handover`,
  render: () => (
    <IframeSurface src="/templates/delivery-runbook/DeliveryRunbook.dc.html" title={`Delivery · Runbook / handover`} />
  ),
};

export const DeliveryStatusEmail = {
  name: `Weekly status email`,
  render: () => (
    <IframeSurface src="/templates/delivery-status-email/DeliveryStatusEmail.dc.html" title={`Delivery · Weekly status email`} />
  ),
};
