/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-template-stories.mjs — do not hand-edit. */
import React from 'react';
import { IframeSurface } from '../../Maintainer/IframeSurface.jsx';

export default {
  title: 'Templates/Documents',
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Design Component starting points from _ds_manifest.json (Atomic View grouping). Portable HTML under templates/.',
      },
    },
  },
};

export const DocStyleGuide = {
  name: `Style Guide`,
  render: () => (
    <IframeSurface src="/templates/doc-style-guide/DocStyleGuide.dc.html" title={`Documents · Style Guide`} />
  ),
};

export const DocSuiteIndex = {
  name: `Suite Index & Usage Guide`,
  render: () => (
    <IframeSurface src="/templates/doc-suite-index/DocSuiteIndex.dc.html" title={`Documents · Suite Index & Usage Guide`} />
  ),
};

export const DocTemplates = {
  name: `Templates`,
  render: () => (
    <IframeSurface src="/templates/doc-templates/DocTemplates.dc.html" title={`Documents · Templates`} />
  ),
};
