/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-template-stories.mjs — do not hand-edit. */
import React from 'react';
import { IframeSurface } from '../../Maintainer/IframeSurface.jsx';

export default {
  title: 'Templates/Finance',
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Design Component starting points from _ds_manifest.json (Atomic View grouping). Portable HTML under templates/.',
      },
    },
  },
};

export const FinanceExpenseReport = {
  name: `Expense report`,
  render: () => (
    <IframeSurface src="/templates/finance-expense-report/FinanceExpenseReport.dc.html" title={`Finance · Expense report`} />
  ),
};

export const FinanceInvoice = {
  name: `Invoice`,
  render: () => (
    <IframeSurface src="/templates/finance-invoice/FinanceInvoice.dc.html" title={`Finance · Invoice`} />
  ),
};

export const FinanceDunningEmail = {
  name: `Payment reminder email`,
  render: () => (
    <IframeSurface src="/templates/finance-dunning-email/FinanceDunningEmail.dc.html" title={`Finance · Payment reminder email`} />
  ),
};

export const FinanceQuote = {
  name: `Quote`,
  render: () => (
    <IframeSurface src="/templates/finance-quote/FinanceQuote.dc.html" title={`Finance · Quote`} />
  ),
};
