/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-template-stories.mjs — do not hand-edit. */
import React from 'react';
import { IframeSurface } from '../../Maintainer/IframeSurface.jsx';

export default {
  title: 'Templates/HR',
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Design Component starting points from _ds_manifest.json (Atomic View grouping). Portable HTML under templates/.',
      },
    },
  },
};

export const VnJobDescription = {
  name: `Bản mô tả công việc — Job Description`,
  render: () => (
    <IframeSurface src="/templates/vn-job-description/VnJobDescription.dc.html" title={`HR Suite · Bản mô tả công việc — Job Description`} />
  ),
};

export const VnDisciplinarySchedule = {
  name: `Bảng xử lý kỷ luật lao động — Disciplinary Schedule`,
  render: () => (
    <IframeSurface src="/templates/vn-disciplinary-schedule/VnDisciplinarySchedule.dc.html" title={`HR Suite · Bảng xử lý kỷ luật lao động — Disciplinary Schedule`} />
  ),
};

export const VnPerformanceReviewForm = {
  name: `Biểu mẫu đánh giá kết quả công việc — Performance Review Form`,
  render: () => (
    <IframeSurface src="/templates/vn-performance-review-form/VnPerformanceReviewForm.dc.html" title={`HR Suite · Biểu mẫu đánh giá kết quả công việc — Performance Review Form`} />
  ),
};

export const VnCodeOfConduct = {
  name: `Bộ Quy tắc Ứng xử — Code of Conduct`,
  render: () => (
    <IframeSurface src="/templates/vn-code-of-conduct/VnCodeOfConduct.dc.html" title={`HR Suite · Bộ Quy tắc Ứng xử — Code of Conduct`} />
  ),
};

export const VnInfosecPolicy = {
  name: `Chính sách An toàn Thông tin & Sử dụng CNTT — Information Security & Acceptable Use Polic`,
  render: () => (
    <IframeSurface src="/templates/vn-infosec-policy/VnInfosecPolicy.dc.html" title={`HR Suite · Chính sách An toàn Thông tin & Sử dụng CNTT — Information Security & Acceptable Use Polic`} />
  ),
};

export const VnDataProtectionPolicy = {
  name: `Chính sách Bảo vệ Dữ liệu Cá nhân — Personal Data Protection Policy`,
  render: () => (
    <IframeSurface src="/templates/vn-data-protection-policy/VnDataProtectionPolicy.dc.html" title={`HR Suite · Chính sách Bảo vệ Dữ liệu Cá nhân — Personal Data Protection Policy`} />
  ),
};

export const VnRemoteWorkPolicy = {
  name: `Chính sách Làm việc Từ xa & Kết hợp — Remote & Hybrid Work Policy`,
  render: () => (
    <IframeSurface src="/templates/vn-remote-work-policy/VnRemoteWorkPolicy.dc.html" title={`HR Suite · Chính sách Làm việc Từ xa & Kết hợp — Remote & Hybrid Work Policy`} />
  ),
};

export const VnOnboardingChecklist = {
  name: `Danh mục hồ sơ & checklist nhận việc — Onboarding Checklist`,
  render: () => (
    <IframeSurface src="/templates/vn-onboarding-checklist/VnOnboardingChecklist.dc.html" title={`HR Suite · Danh mục hồ sơ & checklist nhận việc — Onboarding Checklist`} />
  ),
};

export const VnEmployeeRequest = {
  name: `Đơn đề nghị của người lao động — Employee Request Form`,
  render: () => (
    <IframeSurface src="/templates/vn-employee-request/VnEmployeeRequest.dc.html" title={`HR Suite · Đơn đề nghị của người lao động — Employee Request Form`} />
  ),
};

export const VnResignationLetter = {
  name: `Đơn xin nghỉ việc — Resignation Letter`,
  render: () => (
    <IframeSurface src="/templates/vn-resignation-letter/VnResignationLetter.dc.html" title={`HR Suite · Đơn xin nghỉ việc — Resignation Letter`} />
  ),
};

export const VnPdplConsent = {
  name: `Đồng ý xử lý dữ liệu cá nhân — Personal Data Consent (PDPL)`,
  render: () => (
    <IframeSurface src="/templates/vn-pdpl-consent/VnPdplConsent.dc.html" title={`HR Suite · Đồng ý xử lý dữ liệu cá nhân — Personal Data Consent (PDPL)`} />
  ),
};

export const VnCertificateOfEmployment = {
  name: `Giấy xác nhận quá trình công tác — Certificate of Employment`,
  render: () => (
    <IframeSurface src="/templates/vn-certificate-of-employment/VnCertificateOfEmployment.dc.html" title={`HR Suite · Giấy xác nhận quá trình công tác — Certificate of Employment`} />
  ),
};

export const VnForeignEmployeePack = {
  name: `Hồ sơ lao động người nước ngoài — Foreign Employee Work Permit Pack`,
  render: () => (
    <IframeSurface src="/templates/vn-foreign-employee-pack/VnForeignEmployeePack.dc.html" title={`HR Suite · Hồ sơ lao động người nước ngoài — Foreign Employee Work Permit Pack`} />
  ),
};

export const VnDisciplinaryCaseFile = {
  name: `Hồ sơ xử lý kỷ luật lao động — Disciplinary Case File`,
  render: () => (
    <IframeSurface src="/templates/vn-disciplinary-case-file/VnDisciplinaryCaseFile.dc.html" title={`HR Suite · Hồ sơ xử lý kỷ luật lao động — Disciplinary Case File`} />
  ),
};

export const VnTrainingCommitment = {
  name: `Hợp đồng đào tạo & cam kết — Training & Service Commitment Agreement`,
  render: () => (
    <IframeSurface src="/templates/vn-training-commitment/VnTrainingCommitment.dc.html" title={`HR Suite · Hợp đồng đào tạo & cam kết — Training & Service Commitment Agreement`} />
  ),
};

export const VnContractorAgreement = {
  name: `Hợp đồng dịch vụ (cộng tác viên) — Independent Contractor Agreement`,
  render: () => (
    <IframeSurface src="/templates/vn-contractor-agreement/VnContractorAgreement.dc.html" title={`HR Suite · Hợp đồng dịch vụ (cộng tác viên) — Independent Contractor Agreement`} />
  ),
};

export const VnLaborContract = {
  name: `Hợp đồng lao động — Labor Contract`,
  render: () => (
    <IframeSurface src="/templates/vn-labor-contract/VnLaborContract.dc.html" title={`HR Suite · Hợp đồng lao động — Labor Contract`} />
  ),
};

export const VnFrameworkAgreement = {
  name: `Hợp đồng nguyên tắc — Framework Agreement`,
  render: () => (
    <IframeSurface src="/templates/vn-framework-agreement/VnFrameworkAgreement.dc.html" title={`HR Suite · Hợp đồng nguyên tắc — Framework Agreement`} />
  ),
};

export const VnProbationContract = {
  name: `Hợp đồng thử việc — Probation Contract`,
  render: () => (
    <IframeSurface src="/templates/vn-probation-contract/VnProbationContract.dc.html" title={`HR Suite · Hợp đồng thử việc — Probation Contract`} />
  ),
};

export const HrAnnouncement = {
  name: `Internal announcement`,
  render: () => (
    <IframeSurface src="/templates/hr-announcement/HrAnnouncement.dc.html" title={`HR · Internal announcement`} />
  ),
};

export const HrInterviewKit = {
  name: `Interview kit`,
  render: () => (
    <IframeSurface src="/templates/hr-interview-kit/HrInterviewKit.dc.html" title={`HR · Interview kit`} />
  ),
};

export const VnInternalLaborRegulations = {
  name: `Nội quy lao động — Internal Labor Regulations`,
  render: () => (
    <IframeSurface src="/templates/vn-internal-labor-regulations/VnInternalLaborRegulations.dc.html" title={`HR Suite · Nội quy lao động — Internal Labor Regulations`} />
  ),
};

export const HrOffboarding = {
  name: `Offboarding checklist`,
  render: () => (
    <IframeSurface src="/templates/hr-offboarding/HrOffboarding.dc.html" title={`HR · Offboarding checklist`} />
  ),
};

export const HrPip = {
  name: `Performance improvement plan`,
  render: () => (
    <IframeSurface src="/templates/hr-pip/HrPip.dc.html" title={`HR · Performance improvement plan`} />
  ),
};

export const HrPerformanceReview = {
  name: `Performance review`,
  render: () => (
    <IframeSurface src="/templates/hr-performance-review/HrPerformanceReview.dc.html" title={`HR · Performance review`} />
  ),
};

export const VnReceiptAcknowledgement = {
  name: `Phiếu xác nhận đã nhận tài liệu — Acknowledgement of Receipt`,
  render: () => (
    <IframeSurface src="/templates/vn-receipt-acknowledgement/VnReceiptAcknowledgement.dc.html" title={`HR Suite · Phiếu xác nhận đã nhận tài liệu — Acknowledgement of Receipt`} />
  ),
};

export const VnTotalRewardsAppendix = {
  name: `Phụ lục Đãi ngộ Toàn diện & Lộ trình — Total Rewards & Career Path Appendix`,
  render: () => (
    <IframeSurface src="/templates/vn-total-rewards-appendix/VnTotalRewardsAppendix.dc.html" title={`HR Suite · Phụ lục Đãi ngộ Toàn diện & Lộ trình — Total Rewards & Career Path Appendix`} />
  ),
};

export const VnSowAppendix = {
  name: `Phụ lục phạm vi công việc (SOW) — Statement of Work`,
  render: () => (
    <IframeSurface src="/templates/vn-sow-appendix/VnSowAppendix.dc.html" title={`HR Suite · Phụ lục phạm vi công việc (SOW) — Statement of Work`} />
  ),
};

export const VnContractAmendment = {
  name: `Phụ lục sửa đổi HĐLĐ — Labor Contract Amendment Appendix`,
  render: () => (
    <IframeSurface src="/templates/vn-contract-amendment/VnContractAmendment.dc.html" title={`HR Suite · Phụ lục sửa đổi HĐLĐ — Labor Contract Amendment Appendix`} />
  ),
};

export const VnTravelExpensePolicy = {
  name: `Quy chế Công tác phí & Chi phí — Travel & Expense Policy`,
  render: () => (
    <IframeSurface src="/templates/vn-travel-expense-policy/VnTravelExpensePolicy.dc.html" title={`HR Suite · Quy chế Công tác phí & Chi phí — Travel & Expense Policy`} />
  ),
};

export const VnGrassrootsDemocracy = {
  name: `Quy chế Dân chủ Cơ sở — Grassroots Democracy Regulation`,
  render: () => (
    <IframeSurface src="/templates/vn-grassroots-democracy/VnGrassrootsDemocracy.dc.html" title={`HR Suite · Quy chế Dân chủ Cơ sở — Grassroots Democracy Regulation`} />
  ),
};

export const VnPerformanceEvaluationRegulation = {
  name: `Quy chế Đánh giá Kết quả Công việc — Performance Evaluation Regulation`,
  render: () => (
    <IframeSurface src="/templates/vn-performance-evaluation-regulation/VnPerformanceEvaluationRegulation.dc.html" title={`HR Suite · Quy chế Đánh giá Kết quả Công việc — Performance Evaluation Regulation`} />
  ),
};

export const VnCompensationRegulation = {
  name: `Quy chế Lương, Thưởng & Phúc lợi — Compensation & Reward Regulation`,
  render: () => (
    <IframeSurface src="/templates/vn-compensation-regulation/VnCompensationRegulation.dc.html" title={`HR Suite · Quy chế Lương, Thưởng & Phúc lợi — Compensation & Reward Regulation`} />
  ),
};

export const VnAppointmentTransfer = {
  name: `Quyết định bổ nhiệm / điều chuyển — Appointment & Transfer Decision`,
  render: () => (
    <IframeSurface src="/templates/vn-appointment-transfer/VnAppointmentTransfer.dc.html" title={`HR Suite · Quyết định bổ nhiệm / điều chuyển — Appointment & Transfer Decision`} />
  ),
};

export const VnTerminationDecision = {
  name: `Quyết định chấm dứt HĐLĐ — Decision on Termination`,
  render: () => (
    <IframeSurface src="/templates/vn-termination-decision/VnTerminationDecision.dc.html" title={`HR Suite · Quyết định chấm dứt HĐLĐ — Decision on Termination`} />
  ),
};

export const VnLabourManagementBook = {
  name: `Sổ quản lý lao động — Labour Management Book`,
  render: () => (
    <IframeSurface src="/templates/vn-labour-management-book/VnLabourManagementBook.dc.html" title={`HR Suite · Sổ quản lý lao động — Labour Management Book`} />
  ),
};

export const VnSalaryScale = {
  name: `Thang lương, Bảng lương — Salary Scale & Payroll Table`,
  render: () => (
    <IframeSurface src="/templates/vn-salary-scale/VnSalaryScale.dc.html" title={`HR Suite · Thang lương, Bảng lương — Salary Scale & Payroll Table`} />
  ),
};

export const VnMutualNda = {
  name: `Thỏa thuận bảo mật song phương — Mutual NDA`,
  render: () => (
    <IframeSurface src="/templates/vn-mutual-nda/VnMutualNda.dc.html" title={`HR Suite · Thỏa thuận bảo mật song phương — Mutual NDA`} />
  ),
};

export const VnNdncaIp = {
  name: `Thỏa thuận Bảo mật, KCT & SHTT — NDNCA & IP`,
  render: () => (
    <IframeSurface src="/templates/vn-ndnca-ip/VnNdncaIp.dc.html" title={`HR Suite · Thỏa thuận Bảo mật, KCT & SHTT — NDNCA & IP`} />
  ),
};

export const VnExitHandover = {
  name: `Thỏa thuận chấm dứt HĐLĐ và bàn giao — Exit-Handover Agreement`,
  render: () => (
    <IframeSurface src="/templates/vn-exit-handover/VnExitHandover.dc.html" title={`HR Suite · Thỏa thuận chấm dứt HĐLĐ và bàn giao — Exit-Handover Agreement`} />
  ),
};

export const VnPhantomStock = {
  name: `Thỏa thuận Cổ phần ảo — Phantom Stock Agreement`,
  render: () => (
    <IframeSurface src="/templates/vn-phantom-stock/VnPhantomStock.dc.html" title={`HR Suite · Thỏa thuận Cổ phần ảo — Phantom Stock Agreement`} />
  ),
};

export const VnInternshipAgreement = {
  name: `Thỏa thuận thực tập — Internship Agreement`,
  render: () => (
    <IframeSurface src="/templates/vn-internship-agreement/VnInternshipAgreement.dc.html" title={`HR Suite · Thỏa thuận thực tập — Internship Agreement`} />
  ),
};

export const VnOfferLetter = {
  name: `Thư mời nhận việc — Employment Offer Letter`,
  render: () => (
    <IframeSurface src="/templates/vn-offer-letter/VnOfferLetter.dc.html" title={`HR Suite · Thư mời nhận việc — Employment Offer Letter`} />
  ),
};
