/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-template-stories.mjs — do not hand-edit. */
import React from 'react';
import { IframeSurface } from '../../Maintainer/IframeSurface.jsx';

export default {
  title: 'Templates/Legal',
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Design Component starting points from _ds_manifest.json (Atomic View grouping). Portable HTML under templates/.',
      },
    },
  },
};

export const LegalMsa = {
  name: `Master services agreement`,
  render: () => (
    <IframeSurface src="/templates/legal-msa/LegalMsa.dc.html" title={`Legal · Master services agreement`} />
  ),
};

export const LegalSow = {
  name: `Statement of work`,
  render: () => (
    <IframeSurface src="/templates/legal-sow/LegalSow.dc.html" title={`Legal · Statement of work`} />
  ),
};
