/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-template-stories.mjs — do not hand-edit. */
import React from 'react';
import { IframeSurface } from '../../Maintainer/IframeSurface.jsx';

export default {
  title: 'Templates/Marketing',
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Design Component starting points from _ds_manifest.json (Atomic View grouping). Portable HTML under templates/.',
      },
    },
  },
};

export const MarketingCampaignBrief = {
  name: `Campaign brief`,
  render: () => (
    <IframeSurface src="/templates/marketing-campaign-brief/MarketingCampaignBrief.dc.html" title={`Marketing · Campaign brief`} />
  ),
};

export const MarketingCaseStudy = {
  name: `Case study`,
  render: () => (
    <IframeSurface src="/templates/marketing-case-study/MarketingCaseStudy.dc.html" title={`Marketing · Case study`} />
  ),
};

export const MarketingLaunch = {
  name: `Launch announcement`,
  render: () => (
    <IframeSurface src="/templates/marketing-launch/MarketingLaunch.dc.html" title={`Marketing · Launch announcement`} />
  ),
};

export const MarketingNewsletter = {
  name: `Newsletter`,
  render: () => (
    <IframeSurface src="/templates/marketing-newsletter/MarketingNewsletter.dc.html" title={`Marketing · Newsletter`} />
  ),
};

export const MarketingPressRelease = {
  name: `Press release`,
  render: () => (
    <IframeSurface src="/templates/marketing-press-release/MarketingPressRelease.dc.html" title={`Marketing · Press release`} />
  ),
};

export const MarketingSocialKit = {
  name: `Social post kit`,
  render: () => (
    <IframeSurface src="/templates/marketing-social-kit/MarketingSocialKit.dc.html" title={`Marketing · Social post kit`} />
  ),
};
