/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-template-stories.mjs — do not hand-edit. */
import React from 'react';
import { IframeSurface } from '../../Maintainer/IframeSurface.jsx';

export default {
  title: 'Templates/Product',
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Design Component starting points from _ds_manifest.json (Atomic View grouping). Portable HTML under templates/.',
      },
    },
  },
};

export const AppShell = {
  name: `App shell`,
  render: () => (
    <IframeSurface src="/templates/app-shell/AppShell.dc.html" title={`App shell`} />
  ),
};

export const Article = {
  name: `Article`,
  render: () => (
    <IframeSurface src="/templates/article/Article.dc.html" title={`Article`} />
  ),
};

export const Dashboard = {
  name: `Dashboard`,
  render: () => (
    <IframeSurface src="/templates/dashboard/Dashboard.dc.html" title={`Dashboard`} />
  ),
};

export const Email = {
  name: `Email`,
  render: () => (
    <IframeSurface src="/templates/email/Email.dc.html" title={`Email`} />
  ),
};

export const MarketingPage = {
  name: `Marketing page`,
  render: () => (
    <IframeSurface src="/templates/marketing-page/MarketingPage.dc.html" title={`Marketing page`} />
  ),
};

export const Settings = {
  name: `Settings`,
  render: () => (
    <IframeSurface src="/templates/settings/Settings.dc.html" title={`Settings`} />
  ),
};

export const Auth = {
  name: `Sign in`,
  render: () => (
    <IframeSurface src="/templates/auth/Auth.dc.html" title={`Sign in`} />
  ),
};

export const SlideDeck = {
  name: `Slide deck`,
  render: () => (
    <IframeSurface src="/templates/slide-deck/SlideDeck.dc.html" title={`Slide deck`} />
  ),
};
