/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-template-stories.mjs — do not hand-edit. */
import React from 'react';
import { IframeSurface } from '../../Maintainer/IframeSurface.jsx';

export default {
  title: 'Templates/Sales',
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Design Component starting points from _ds_manifest.json (Atomic View grouping). Portable HTML under templates/.',
      },
    },
  },
};

export const SalesOnePager = {
  name: `One-pager`,
  render: () => (
    <IframeSurface src="/templates/sales-one-pager/SalesOnePager.dc.html" title={`Sales · One-pager`} />
  ),
};

export const SalesProposalDeck = {
  name: `Proposal deck`,
  render: () => (
    <IframeSurface src="/templates/sales-proposal-deck/SalesProposalDeck.dc.html" title={`Sales · Proposal deck`} />
  ),
};
