/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-template-stories.mjs — do not hand-edit. */
import React from 'react';
import { IframeSurface } from '../../Maintainer/IframeSurface.jsx';

export default {
  title: 'Templates/Team',
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Design Component starting points from _ds_manifest.json (Atomic View grouping). Portable HTML under templates/.',
      },
    },
  },
};

export const TeamMeetingAgenda = {
  name: `Meeting agenda`,
  render: () => (
    <IframeSurface src="/templates/team-meeting-agenda/TeamMeetingAgenda.dc.html" title={`Team · Meeting agenda`} />
  ),
};
