/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-template-stories.mjs — do not hand-edit. */
import React from 'react';
import { IframeSurface } from '../../Maintainer/IframeSurface.jsx';

export default {
  title: 'Templates/Tech',
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Design Component starting points from _ds_manifest.json (Atomic View grouping). Portable HTML under templates/.',
      },
    },
  },
};

export const TechIncidentReport = {
  name: `Incident report`,
  render: () => (
    <IframeSurface src="/templates/tech-incident-report/TechIncidentReport.dc.html" title={`Tech · Incident report`} />
  ),
};

export const TechReleaseNotes = {
  name: `Release notes email`,
  render: () => (
    <IframeSurface src="/templates/tech-release-notes/TechReleaseNotes.dc.html" title={`Tech · Release notes email`} />
  ),
};

export const TechRfc = {
  name: `RFC / design doc`,
  render: () => (
    <IframeSurface src="/templates/tech-rfc/TechRfc.dc.html" title={`Tech · RFC / design doc`} />
  ),
};

export const TechRetro = {
  name: `Sprint retro`,
  render: () => (
    <IframeSurface src="/templates/tech-retro/TechRetro.dc.html" title={`Tech · Sprint retro`} />
  ),
};
