#!/usr/bin/env node
/** Flatten styles.css @import chain → dist/styles.min.css (UX-027 / C7). */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join, resolve } from 'path';
import { fileURLToPath } from 'url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const seen = new Set();

function flatten(absPath) {
  const key = resolve(absPath);
  if (seen.has(key)) return '';
  seen.add(key);
  const text = readFileSync(key, 'utf8');
  const out = [];
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(/^\s*@import\s+(?:url\()?['"]([^'"]+)['"]\)?\s*;/);
    if (m) {
      const child = resolve(dirname(key), m[1]);
      out.push(flatten(child));
    } else {
      out.push(line);
    }
  }
  return out.join('\n') + '\n';
}

const css = flatten(join(ROOT, 'styles.css'));
let min = css.replace(/\/\*[\s\S]*?\*\//g, '');
min = min.replace(/\n{3,}/g, '\n\n').replace(/[ \t]+/g, ' ').replace(/\n /g, '\n');
if (min.includes('@import')) {
  console.error('flatten-styles: residual @import after flatten');
  process.exit(1);
}
mkdirSync(join(ROOT, 'dist'), { recursive: true });
const banner = '/* CyberSkill Design System — flattened styles (generated by scripts/flatten-styles.mjs). Source: styles.css + tokens/ + base/. */\n';
const outPath = join(ROOT, 'dist', 'styles.min.css');
writeFileSync(outPath, banner + min);
console.log('wrote', outPath, '(' + Buffer.byteLength(banner + min) + ' bytes)');
