#!/usr/bin/env node
/** Flatten styles.css @import chain → dist/styles.min.css (UX-027 / C7). */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { dirname, join, resolve } from 'path';
import { fileURLToPath } from 'url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outPath = join(ROOT, 'dist', 'styles.min.css');
const args = new Set(process.argv.slice(2));
const checkOnly = args.has('--check');

function flatten(absPath, seen = new Set()) {
  const key = resolve(absPath);
  if (seen.has(key)) return '';
  seen.add(key);
  const text = readFileSync(key, 'utf8');
  const out = [];
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(/^\s*@import\s+(?:url\()?['"]([^'"]+)['"]\)?\s*;/);
    if (m) {
      const child = resolve(dirname(key), m[1]);
      out.push(flatten(child, seen));
    } else {
      out.push(line);
    }
  }
  return out.join('\n') + '\n';
}

function buildFlattened() {
  const css = flatten(join(ROOT, 'styles.css'));
  let min = css.replace(/\/\*[\s\S]*?\*\//g, '');
  min = min.replace(/\n{3,}/g, '\n\n').replace(/[ \t]+/g, ' ').replace(/\n /g, '\n');
  if (min.includes('@import')) {
    throw new Error('flatten-styles: residual @import after flatten');
  }
  const banner =
    '/* CyberSkill Design System — flattened styles (generated by scripts/flatten-styles.mjs). Source: styles.css + tokens/ + base/. */\n';
  return banner + min;
}

function main() {
  const next = buildFlattened();
  if (checkOnly) {
    if (!existsSync(outPath)) {
      console.error('FAIL flatten-styles --check: dist/styles.min.css missing. Run: npm run build:styles');
      process.exit(1);
    }
    const current = readFileSync(outPath, 'utf8');
    if (current !== next) {
      console.error('FAIL flatten-styles --check: dist/styles.min.css drifted from styles.css + tokens/ + base/. Rebuild: npm run build:styles');
      process.exit(1);
    }
    console.log('PASS flatten-styles --check (' + Buffer.byteLength(current) + ' bytes)');
    return;
  }
  mkdirSync(join(ROOT, 'dist'), { recursive: true });
  writeFileSync(outPath, next);
  console.log('wrote', outPath, '(' + Buffer.byteLength(next) + ' bytes)');
}

main();
