// CyberSkill Design System — native design tokens.
// GENERATED from tokens/tokens.dtcg.json — do not hand-edit; regenerate on token change.
// release v1.0.0 · source sha256 9918e62b18dc47f0…
// conversions: rem→px at 16 · em→…Em relative doubles · rgba alpha→ARGB byte (round(a*255)) · durations in ms
// dark element packs: see $extensions.overrides.elementsDark
// provenance: tokens/provenance.json · parity gate: _audit/token-pipeline-test.html

import SwiftUI

public enum CSTokens {
  /// 0xRRGGBB (+ alpha param) → SwiftUI Color
  public static func color(_ hex: UInt32, alpha: Double = 1) -> Color {
    Color(red: Double((hex >> 16) & 0xFF)/255, green: Double((hex >> 8) & 0xFF)/255, blue: Double(hex & 0xFF)/255, opacity: alpha)
  }

  public static let colorBrandUmber = color(0x45210E)
  public static let colorBrandOchre = color(0xF4BA17)
  public static let colorSurfacePage = color(0xFFFDF8)
  public static let colorSurfacePanel = color(0xFFFFFF)
  public static let colorSurfaceRaised = color(0xFBF4E9)
  public static let colorTextPrimary = color(0x45210E)
  public static let colorTextInverse = color(0xFFFFFF)
  public static let colorTextAccent = color(0x6E3B0E)
  public static let colorTextMuted = color(0x6E5A4C)
  public static let colorSemanticSuccess = color(0x166534)
  public static let colorSemanticDanger = color(0xB42318)
  public static let colorSemanticWarning = color(0x92400E)
  public static let colorSemanticInfo = color(0x1D4ED8)
  public static let colorAccentOchre = color(0xF4BA17)
  public static let colorBorderDefault = color(0xE7D9C6)
  public static let colorLink = color(0x6E3B0E)
  public static let colorLinkHover = color(0x45210E)
  public static let componentButtonPrimaryBg = color(0x45210E)
  public static let componentButtonPrimaryFg = color(0xFFFFFF)
  public static let componentButtonGap: CGFloat = 8
  public static let componentButtonRadius: CGFloat = 8
  public static let componentButtonXsPaddingY: CGFloat = 4
  public static let componentButtonXsPaddingX: CGFloat = 10
  public static let componentButtonXsMinHeight: CGFloat = 28
  public static let componentButtonXsMinWidth: CGFloat = 28
  public static let componentButtonXsMinHeightCoarse: CGFloat = 36
  public static let componentButtonSmPaddingY: CGFloat = 8
  public static let componentButtonSmPaddingX: CGFloat = 14
  public static let componentButtonSmMinHeight: CGFloat = 36
  public static let componentButtonSmMinHeightCoarse: CGFloat = 40
  public static let componentButtonMdPaddingY: CGFloat = 12
  public static let componentButtonMdPaddingX: CGFloat = 20
  public static let componentButtonMdMinHeight: CGFloat = 44
  public static let componentButtonMdMinHeightCoarse: CGFloat = 44
  public static let componentButtonLgPaddingY: CGFloat = 16
  public static let componentButtonLgPaddingX: CGFloat = 28
  public static let componentButtonLgMinHeight: CGFloat = 52
  public static let componentTextfieldBorderDefault = color(0xBFA58F)
  public static let componentTextfieldPaddingY: CGFloat = 10
  public static let componentTextfieldPaddingX: CGFloat = 12
  public static let componentTextfieldMinHeight: CGFloat = 44
  public static let accent = color(0xF4BA17)
  public static let accentStrong = color(0x9E770B)
  public static let accentBright = color(0xF4BA17)
  public static let accentOn = color(0x45210E)
  public static let accentTint = color(0xFBF4E9)
  public static let accentInk = color(0x45210E)
  public static let accentGlow = color(0xF4BA17, alpha: 0.5)
  public static let accentGradA = color(0xF4BA17)
  public static let accentGradB = color(0xFFAD8E)
  public static let depthBg: Double = 0
  public static let depthSection: Double = 5
  public static let depthCard: Double = 10
  public static let depthNav: Double = 50
  public static let depthModal: Double = 100
  public static let depthToast: Double = 200
  public static let glassWhisperBlur: CGFloat = 8
  public static let glassWhisperSaturate: String = "110%"
  public static let glassWhisperOpacity: String = "60%"
  public static let glassLightBlur: CGFloat = 12
  public static let glassLightSaturate: String = "130%"
  public static let glassLightOpacity: String = "70%"
  public static let glassStandardBlur: CGFloat = 16
  public static let glassStandardSaturate: String = "150%"
  public static let glassStandardOpacity: String = "80%"
  public static let glassHeavyBlur: CGFloat = 24
  public static let glassHeavySaturate: String = "180%"
  public static let glassHeavyOpacity: String = "90%"
  public static let shadowXs: String = "0 1px 2px rgba(69, 33, 14, 0.06)"
  public static let shadowSm: String = "0 1px 3px rgba(69, 33, 14, 0.04), 0 8px 24px rgba(69, 33, 14, 0.06)"
  public static let shadowMd: String = "0 12px 30px rgba(31, 19, 11, 0.18)"
  public static let shadowLg: String = "0 20px 60px rgba(69, 33, 14, 0.18)"
  public static let shadowXl: String = "0 24px 80px rgba(31, 19, 11, 0.26)"
  public static let durationInstantMs: Double = 80
  public static let durationFastMs: Double = 120
  public static let durationBaseMs: Double = 200
  public static let durationSlowMs: Double = 320
  public static let easeStandard: [Double] = [0.2, 0, 0, 1]
  public static let easeEntrance: [Double] = [0, 0, 0, 1]
  public static let easeExit: [Double] = [0.4, 0, 1, 1]
  public static let easeEmphasized: [Double] = [0.2, 0, 0, 1]
  public static let space0: CGFloat = 0
  public static let space1: CGFloat = 4
  public static let space2: CGFloat = 8
  public static let space3: CGFloat = 12
  public static let space4: CGFloat = 16
  public static let space5: CGFloat = 20
  public static let space6: CGFloat = 24
  public static let space8: CGFloat = 32
  public static let space10: CGFloat = 40
  public static let space12: CGFloat = 48
  public static let space16: CGFloat = 64
  public static let space20: CGFloat = 80
  public static let space24: CGFloat = 96
  public static let radiusSm: CGFloat = 4
  public static let radiusMd: CGFloat = 8
  public static let radiusLg: CGFloat = 14
  public static let radiusFull: CGFloat = 999
  public static let breakpointXs: CGFloat = 0
  public static let breakpointSm: CGFloat = 640
  public static let breakpointMd: CGFloat = 768
  public static let breakpointLg: CGFloat = 1024
  public static let breakpointXl: CGFloat = 1280
  public static let breakpoint2xl: CGFloat = 1536
  public static let containerMax: CGFloat = 1320
  public static let fontFamilyUi: String = "Be Vietnam Pro, ui-sans-serif, system-ui, sans-serif"
  public static let fontFamilyDisplay: String = "Space Grotesk, Be Vietnam Pro, ui-sans-serif, system-ui, sans-serif"
  public static let fontFamilyMono: String = "JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
  public static let fontWeightRegular: Double = 400
  public static let fontWeightMedium: Double = 500
  public static let fontWeightSemibold: Double = 600
  public static let fontWeightBold: Double = 700
  public static let fontWeightExtrabold: Double = 800
  public static let fontLineHeightBody: Double = 1.5
  public static let fontLineHeightHeading: Double = 1.35
  public static let fontLineHeightTight: Double = 1.15
  public static let fontSizeXs: CGFloat = 12
  public static let fontSizeSm: CGFloat = 14
  public static let fontSizeBase: CGFloat = 16
  public static let fontSizeMd: CGFloat = 18
  public static let fontSizeLg: CGFloat = 20
  public static let fontSizeXl: CGFloat = 24
  public static let fontSize2xl: CGFloat = 30
  public static let fontSize3xl: CGFloat = 36
  public static let fontSize4xl: CGFloat = 48
  public static let fontSize5xl: CGFloat = 60
  public static let textDisplay: String = "var(--cs-font-size-5xl)"
  public static let textH1: String = "var(--cs-font-size-3xl)"
  public static let textH2: String = "var(--cs-font-size-2xl)"
  public static let textH3: String = "var(--cs-font-size-xl)"
  public static let textH4: String = "var(--cs-font-size-lg)"
  public static let textBodyLg: String = "var(--cs-font-size-md)"
  public static let textBody: String = "var(--cs-font-size-base)"
  public static let textSecondary: String = "var(--cs-font-size-sm)"
  public static let textCaption: String = "var(--cs-font-size-xs)"
  public static let textEyebrow: String = "var(--cs-font-size-xs)"
  public static let letterSpacingTightEm: Double = -0.01
  public static let letterSpacingNormal: Double = 0
  public static let letterSpacingCapsEm: Double = 0.08
  public static let headingFamily: String = "var(--cs-font-family-ui)"
  public static let headingWeightStrong: String = "var(--cs-font-weight-extrabold)"
  public static let headingWeight: String = "var(--cs-font-weight-bold)"
  public static let headingTracking: String = "var(--cs-letter-spacing-tight)"
  public static let iconSm: CGFloat = 16
  public static let iconMd: CGFloat = 20
  public static let iconLg: CGFloat = 24

  // MARK: dark-theme color overrides
  public static let colorSurfacePageDark = color(0x1A1108)
  public static let colorSurfacePanelDark = color(0x221710)
  public static let colorSurfaceRaisedDark = color(0x2B1E14)
  public static let colorTextPrimaryDark = color(0xF5EAD9)
  public static let colorTextInverseDark = color(0x1A1108)
  public static let colorTextAccentDark = color(0xF4BA17)
  public static let colorTextMutedDark = color(0xC9B7A3)
  public static let colorSemanticSuccessDark = color(0x4ADE80)
  public static let colorSemanticDangerDark = color(0xF87171)
  public static let colorSemanticWarningDark = color(0xFBBF24)
  public static let colorSemanticInfoDark = color(0x7CB2FB)
  public static let colorBorderDefaultDark = color(0x4A3A2C)
  public static let colorLinkDark = color(0xF4BA17)
  public static let colorLinkHoverDark = color(0xF5EAD9)
  public static let componentButtonPrimaryBgDark = color(0xF4BA17)
  public static let componentButtonPrimaryFgDark = color(0x1A1108)
  public static let componentTextfieldBorderDefaultDark = color(0x5A4636)

  // MARK: dark elemental accent packs (APCA-derived, v4.0.0)
  public static let accentThoSandDark = color(0xFAECB2)
  public static let accentBrightThoSandDark = color(0xF6ECC1)
  public static let accentStrongThoSandDark = color(0x665A27)
  public static let accentOnThoSandDark = color(0xF5EAD9)
  public static let accentTintThoSandDark = color(0x2B2403)
  public static let accentInkThoSandDark = color(0xF6ECC1)
  public static let accentThoDark = color(0xF4BA17)
  public static let accentBrightThoDark = color(0xFEC42C)
  public static let accentStrongThoDark = color(0x73560B)
  public static let accentOnThoDark = color(0xF5EAD9)
  public static let accentTintThoDark = color(0x2F2203)
  public static let accentInkThoDark = color(0xFEC849)
  public static let accentThoClayDark = color(0xD9AC66)
  public static let accentBrightThoClayDark = color(0xFDC672)
  public static let accentStrongThoClayDark = color(0x4C3201)
  public static let accentOnThoClayDark = color(0xF5EAD9)
  public static let accentTintThoClayDark = color(0x312003)
  public static let accentInkThoClayDark = color(0xFDC672)
  public static let accentHoaPlasmaDark = color(0xFFE3E6)
  public static let accentBrightHoaPlasmaDark = color(0xFFE3E6)
  public static let accentStrongHoaPlasmaDark = color(0x923E4E)
  public static let accentOnHoaPlasmaDark = color(0xF5EAD9)
  public static let accentTintHoaPlasmaDark = color(0x311E20)
  public static let accentInkHoaPlasmaDark = color(0xFFE3E6)
  public static let accentHoaDark = color(0xFFAD8E)
  public static let accentBrightHoaDark = color(0xFFCAB6)
  public static let accentStrongHoaDark = color(0x9B3C0F)
  public static let accentOnHoaDark = color(0xF5EAD9)
  public static let accentTintHoaDark = color(0x381B10)
  public static let accentInkHoaDark = color(0xFFCAB6)
  public static let accentHoaLavaDark = color(0xF2A16A)
  public static let accentBrightHoaLavaDark = color(0xFEC39C)
  public static let accentStrongHoaLavaDark = color(0x572A04)
  public static let accentOnHoaLavaDark = color(0xF5EAD9)
  public static let accentTintHoaLavaDark = color(0x361D0A)
  public static let accentInkHoaLavaDark = color(0xFEC8A5)
  public static let accentThuyMistDark = color(0xB4FAFC)
  public static let accentBrightThuyMistDark = color(0xC3F7F8)
  public static let accentStrongThuyMistDark = color(0x206365)
  public static let accentOnThuyMistDark = color(0xF5EAD9)
  public static let accentTintThuyMistDark = color(0x022A2B)
  public static let accentInkThuyMistDark = color(0xC3F7F8)
  public static let accentThuyDark = color(0x87D2E1)
  public static let accentBrightThuyDark = color(0xACE2ED)
  public static let accentStrongThuyDark = color(0x176370)
  public static let accentOnThuyDark = color(0xF5EAD9)
  public static let accentTintThuyDark = color(0x032930)
  public static let accentInkThuyDark = color(0xACE2ED)
  public static let accentThuyOceanDark = color(0x65BEDF)
  public static let accentBrightThuyOceanDark = color(0x8DDAF7)
  public static let accentStrongThuyOceanDark = color(0x063E4F)
  public static let accentOnThuyOceanDark = color(0xF5EAD9)
  public static let accentTintThuyOceanDark = color(0x032934)
  public static let accentInkThuyOceanDark = color(0x90DDFA)
  public static let accentMocBambooDark = color(0xEAF3AD)
  public static let accentBrightMocBambooDark = color(0xEAF1BD)
  public static let accentStrongMocBambooDark = color(0x5A6021)
  public static let accentOnMocBambooDark = color(0xF5EAD9)
  public static let accentTintMocBambooDark = color(0x242706)
  public static let accentInkMocBambooDark = color(0xEAF1BD)
  public static let accentMocDark = color(0xADD386)
  public static let accentBrightMocDark = color(0xC6E3AA)
  public static let accentStrongMocDark = color(0x45641C)
  public static let accentOnMocDark = color(0xF5EAD9)
  public static let accentTintMocDark = color(0x1C290D)
  public static let accentInkMocDark = color(0xC6E3AA)
  public static let accentMocForestDark = color(0x77C777)
  public static let accentBrightMocForestDark = color(0xA1DDA0)
  public static let accentStrongMocForestDark = color(0x08450E)
  public static let accentOnMocForestDark = color(0xF5EAD9)
  public static let accentTintMocForestDark = color(0x142A14)
  public static let accentInkMocForestDark = color(0xA4E0A3)
  public static let accentKimTitaniumDark = color(0xFFE6D3)
  public static let accentBrightKimTitaniumDark = color(0xFBE7D8)
  public static let accentStrongKimTitaniumDark = color(0x6B5646)
  public static let accentOnKimTitaniumDark = color(0xF5EAD9)
  public static let accentTintKimTitaniumDark = color(0x311F11)
  public static let accentInkKimTitaniumDark = color(0xFBE7D8)
  public static let accentKimDark = color(0xD1C2A8)
  public static let accentBrightKimDark = color(0xE1D6C2)
  public static let accentStrongKimDark = color(0x655944)
  public static let accentOnKimDark = color(0xF5EAD9)
  public static let accentTintKimDark = color(0x2E220C)
  public static let accentInkKimDark = color(0xE1D6C2)
  public static let accentKimSteelDark = color(0x8FBFC0)
  public static let accentBrightKimSteelDark = color(0xB2D6D6)
  public static let accentStrongKimSteelDark = color(0x134041)
  public static let accentOnKimSteelDark = color(0xF5EAD9)
  public static let accentTintKimSteelDark = color(0x022A2B)
  public static let accentInkKimSteelDark = color(0xB5D9D9)
}
