// CyberSkill Design System — native design tokens.
// GENERATED from tokens/tokens.dtcg.json — do not hand-edit; regenerate on token change.
// release v1.7.2 · source sha256 c6ea7d6ade8c7c61…
// conversions: rem→px at 16 · em→…Em relative doubles · rgba alpha→ARGB byte (round(a*255)) · durations in ms
// dark element packs: see $extensions.overrides.elementsDark
// provenance: tokens/provenance.json · parity gate: _audit/token-pipeline-test.html

import SwiftUI

public enum CSTokens {
  /// 0xRRGGBB (+ alpha param) → SwiftUI Color
  public static func color(_ hex: UInt32, alpha: Double = 1) -> Color {
    Color(red: Double((hex >> 16) & 0xFF)/255, green: Double((hex >> 8) & 0xFF)/255, blue: Double(hex & 0xFF)/255, opacity: alpha)
  }

  public static let colorBrandUmber = color(0x45210E)
  public static let colorBrandOchre = color(0xF4BA17)
  public static let colorSurfacePage = color(0xFFFDF8)
  public static let colorSurfacePanel = color(0xFFFFFF)
  public static let colorSurfaceRaised = color(0xFBF4E9)
  public static let colorTextPrimary = color(0x45210E)
  public static let colorTextInverse = color(0xFFFFFF)
  public static let colorTextAccent = color(0x6E3B0E)
  public static let colorTextMuted = color(0x6E5A4C)
  public static let colorSemanticSuccess = color(0x166534)
  public static let colorSemanticDanger = color(0xB42318)
  public static let colorSemanticWarning = color(0x92400E)
  public static let colorSemanticInfo = color(0x1D4ED8)
  public static let colorAccentOchre = color(0xF4BA17)
  public static let colorBorderDefault = color(0xE7D9C6)
  public static let colorLink = color(0x6E3B0E)
  public static let colorLinkHover = color(0x45210E)
  public static let colorSemanticSuccessFg = color(0xFFFFFF)
  public static let colorSemanticDangerFg = color(0xFFFFFF)
  public static let colorSemanticWarningFg = color(0xFFFFFF)
  public static let colorSemanticInfoFg = color(0xFFFFFF)
  public static let componentButtonPrimaryBg = color(0x45210E)
  public static let componentButtonPrimaryFg = color(0xFFFFFF)
  public static let componentButtonGap: CGFloat = 8
  public static let componentButtonRadius: CGFloat = 8
  public static let componentButtonXsPaddingY: CGFloat = 4
  public static let componentButtonXsPaddingX: CGFloat = 10
  public static let componentButtonXsMinHeight: CGFloat = 28
  public static let componentButtonXsMinWidth: CGFloat = 28
  public static let componentButtonXsMinHeightCoarse: CGFloat = 44
  public static let componentButtonSmPaddingY: CGFloat = 8
  public static let componentButtonSmPaddingX: CGFloat = 14
  public static let componentButtonSmMinHeight: CGFloat = 36
  public static let componentButtonSmMinHeightCoarse: CGFloat = 44
  public static let componentButtonMdPaddingY: CGFloat = 12
  public static let componentButtonMdPaddingX: CGFloat = 20
  public static let componentButtonMdMinHeight: CGFloat = 44
  public static let componentButtonMdMinHeightCoarse: CGFloat = 44
  public static let componentButtonLgPaddingY: CGFloat = 16
  public static let componentButtonLgPaddingX: CGFloat = 28
  public static let componentButtonLgMinHeight: CGFloat = 52
  public static let componentTextfieldBorderDefault = color(0xBFA58F)
  public static let componentTextfieldPaddingY: CGFloat = 10
  public static let componentTextfieldPaddingX: CGFloat = 12
  public static let componentTextfieldMinHeight: CGFloat = 44
  public static let focusRing: CGFloat = 3
  public static let accent = color(0xF4BA17)
  public static let accentStrong = color(0xA47D17)
  public static let accentBright = color(0xF4BA17)
  public static let accentOn = color(0x45210E)
  public static let accentTint = color(0xFBF4E9)
  public static let accentInk = color(0x45210E)
  public static let accentGlow = color(0xF4BA17, alpha: 0.48)
  public static let accentGradA = color(0xF4BA17)
  public static let accentGradB = color(0xF3B958)
  public static let accentOnStrong = color(0x1A1108)
  public static let depthBg: Double = 0
  public static let depthSection: Double = 5
  public static let depthCard: Double = 10
  public static let depthNav: Double = 50
  public static let depthModal: Double = 100
  public static let depthToast: Double = 200
  public static let depthDropdown: Double = 60
  public static let depthOverlay: Double = 80
  public static let glassWhisperBlur: CGFloat = 8
  public static let glassWhisperSaturate: String = "110%"
  public static let glassWhisperOpacity: String = "60%"
  public static let glassLightBlur: CGFloat = 12
  public static let glassLightSaturate: String = "130%"
  public static let glassLightOpacity: String = "70%"
  public static let glassStandardBlur: CGFloat = 16
  public static let glassStandardSaturate: String = "150%"
  public static let glassStandardOpacity: String = "80%"
  public static let glassHeavyBlur: CGFloat = 24
  public static let glassHeavySaturate: String = "180%"
  public static let glassHeavyOpacity: String = "90%"
  public static let shadowXs: String = "0 1px 2px rgba(69, 33, 14, 0.06)"
  public static let shadowSm: String = "0 1px 3px rgba(69, 33, 14, 0.04), 0 8px 24px rgba(69, 33, 14, 0.06)"
  public static let shadowMd: String = "0 12px 30px rgba(31, 19, 11, 0.18)"
  public static let shadowLg: String = "0 20px 60px rgba(69, 33, 14, 0.18)"
  public static let shadowXl: String = "0 24px 80px rgba(31, 19, 11, 0.26)"
  public static let durationInstantMs: Double = 80
  public static let durationFastMs: Double = 120
  public static let durationBaseMs: Double = 200
  public static let durationSlowMs: Double = 320
  public static let easeStandard: [Double] = [0.2, 0, 0, 1]
  public static let easeEntrance: [Double] = [0, 0, 0, 1]
  public static let easeExit: [Double] = [0.4, 0, 1, 1]
  public static let easeEmphasized: [Double] = [0.2, 0, 0, 1]
  public static let space0: CGFloat = 0
  public static let space1: CGFloat = 4
  public static let space2: CGFloat = 8
  public static let space3: CGFloat = 12
  public static let space4: CGFloat = 16
  public static let space5: CGFloat = 20
  public static let space6: CGFloat = 24
  public static let space8: CGFloat = 32
  public static let space10: CGFloat = 40
  public static let space12: CGFloat = 48
  public static let space16: CGFloat = 64
  public static let space20: CGFloat = 80
  public static let space24: CGFloat = 96
  public static let radiusSm: CGFloat = 4
  public static let radiusMd: CGFloat = 8
  public static let radiusLg: CGFloat = 14
  public static let radiusFull: CGFloat = 999
  public static let breakpointXs: CGFloat = 0
  public static let breakpointPhone: CGFloat = 360
  public static let breakpointSm: CGFloat = 640
  public static let breakpointMd: CGFloat = 768
  public static let breakpointLg: CGFloat = 1024
  public static let breakpointXl: CGFloat = 1280
  public static let breakpoint2xl: CGFloat = 1536
  public static let containerMax: CGFloat = 1320
  public static let proseMeasure: CGFloat = 720
  public static let scrollPaddingBlockStart: String = "var(--cs-space-4)"
  public static let scrollPaddingBlockEnd: String = "var(--cs-space-4)"
  public static let fontFamilyUi: String = "Be Vietnam Pro, ui-sans-serif, system-ui, sans-serif"
  public static let fontFamilyDisplay: String = "Space Grotesk, Be Vietnam Pro, ui-sans-serif, system-ui, sans-serif"
  public static let fontFamilyMono: String = "JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
  public static let fontWeightRegular: Double = 400
  public static let fontWeightMedium: Double = 500
  public static let fontWeightSemibold: Double = 600
  public static let fontWeightBold: Double = 700
  public static let fontWeightExtrabold: Double = 800
  public static let fontLineHeightBody: Double = 1.5
  public static let fontLineHeightHeading: Double = 1.35
  public static let fontLineHeightTight: Double = 1.15
  public static let fontSize2xs: CGFloat = 11
  public static let fontSizeXs: CGFloat = 12
  public static let fontSizeSm: CGFloat = 14
  public static let fontSizeBase: CGFloat = 16
  public static let fontSizeMd: CGFloat = 18
  public static let fontSizeLg: CGFloat = 20
  public static let fontSizeXl: CGFloat = 24
  public static let fontSize2xl: CGFloat = 30
  public static let fontSize3xl: CGFloat = 36
  public static let fontSize4xl: CGFloat = 48
  public static let fontSize5xl: CGFloat = 60
  public static let textDisplay: String = "var(--cs-font-size-5xl)"
  public static let textH1: String = "var(--cs-font-size-3xl)"
  public static let textH2: String = "var(--cs-font-size-2xl)"
  public static let textH3: String = "var(--cs-font-size-xl)"
  public static let textH4: String = "var(--cs-font-size-lg)"
  public static let textBodyLg: String = "var(--cs-font-size-md)"
  public static let textBody: String = "var(--cs-font-size-base)"
  public static let textSecondary: String = "var(--cs-font-size-sm)"
  public static let textMicro: String = "var(--cs-font-size-2xs)"
  public static let textCaption: String = "var(--cs-font-size-xs)"
  public static let textEyebrow: String = "var(--cs-font-size-xs)"
  public static let letterSpacingTightEm: Double = -0.01
  public static let letterSpacingNormal: Double = 0
  public static let letterSpacingCapsEm: Double = 0.08
  public static let headingFamily: String = "var(--cs-font-family-ui)"
  public static let headingWeightStrong: String = "var(--cs-font-weight-extrabold)"
  public static let headingWeight: String = "var(--cs-font-weight-bold)"
  public static let headingTracking: String = "var(--cs-letter-spacing-tight)"
  public static let iconSm: CGFloat = 16
  public static let iconMd: CGFloat = 20
  public static let iconLg: CGFloat = 24
  public static let docInk = color(0x1A1614)
  public static let docSlate = color(0x3F4C55)
  public static let docFill = color(0xFDE68A)
  public static let docFillInk = color(0x1A1614)
  public static let densitySpace1: CGFloat = 4
  public static let densitySpace2: CGFloat = 8
  public static let densitySpace3: CGFloat = 12
  public static let densitySpace4: CGFloat = 16
  public static let densitySpace5: CGFloat = 20
  public static let densitySpace6: CGFloat = 24
  public static let densityControlGap: CGFloat = 8

  // MARK: dark-theme color overrides
  public static let colorSurfacePageDark = color(0x1A1108)
  public static let colorSurfacePanelDark = color(0x221710)
  public static let colorSurfaceRaisedDark = color(0x2B1E14)
  public static let colorTextPrimaryDark = color(0xF5EAD9)
  public static let colorTextInverseDark = color(0x1A1108)
  public static let colorTextAccentDark = color(0xF4BA17)
  public static let colorTextMutedDark = color(0xC9B7A3)
  public static let colorSemanticSuccessDark = color(0x4ADE80)
  public static let colorSemanticDangerDark = color(0xF87171)
  public static let colorSemanticWarningDark = color(0xFBBF24)
  public static let colorSemanticInfoDark = color(0x7CB2FB)
  public static let colorSemanticSuccessFgDark = color(0x1A1108)
  public static let colorSemanticDangerFgDark = color(0x1A1108)
  public static let colorSemanticWarningFgDark = color(0x1A1108)
  public static let colorSemanticInfoFgDark = color(0x1A1108)
  public static let colorBorderDefaultDark = color(0x4A3A2C)
  public static let colorLinkDark = color(0xF4BA17)
  public static let colorLinkHoverDark = color(0xF5EAD9)
  public static let componentButtonPrimaryBgDark = color(0xF4BA17)
  public static let componentButtonPrimaryFgDark = color(0x1A1108)
  public static let componentTextfieldBorderDefaultDark = color(0x5A4636)
  public static let shadowXsDark: String = "0 1px 2px rgba(0, 0, 0, 0.40)"
  public static let shadowSmDark: String = "0 1px 3px rgba(0, 0, 0, 0.34), 0 8px 24px rgba(0, 0, 0, 0.42)"
  public static let shadowMdDark: String = "0 12px 30px rgba(0, 0, 0, 0.50)"
  public static let shadowLgDark: String = "0 20px 60px rgba(0, 0, 0, 0.55)"
  public static let shadowXlDark: String = "0 24px 80px rgba(0, 0, 0, 0.62)"

  // compact-density Theme metrics
  public static let densitySpace1Compact: CGFloat = 3
  public static let densitySpace2Compact: CGFloat = 6
  public static let densitySpace3Compact: CGFloat = 9
  public static let densitySpace4Compact: CGFloat = 12
  public static let densitySpace5Compact: CGFloat = 16
  public static let densitySpace6Compact: CGFloat = 18
  public static let densityControlGapCompact: CGFloat = 6
  public static let componentButtonGapCompact: CGFloat = 6
  public static let componentButtonXsPaddingYCompact: CGFloat = 3
  public static let componentButtonXsPaddingXCompact: CGFloat = 8
  public static let componentButtonSmPaddingYCompact: CGFloat = 6
  public static let componentButtonSmPaddingXCompact: CGFloat = 12
  public static let componentButtonMdPaddingYCompact: CGFloat = 10
  public static let componentButtonMdPaddingXCompact: CGFloat = 16
  public static let componentButtonLgPaddingYCompact: CGFloat = 12
  public static let componentButtonLgPaddingXCompact: CGFloat = 22
  public static let componentTextfieldPaddingYCompact: CGFloat = 8
  public static let componentTextfieldPaddingXCompact: CGFloat = 10

  // comfortable-density Theme metrics
  public static let densitySpace1Comfortable: CGFloat = 4
  public static let densitySpace2Comfortable: CGFloat = 8
  public static let densitySpace3Comfortable: CGFloat = 12
  public static let densitySpace4Comfortable: CGFloat = 16
  public static let densitySpace5Comfortable: CGFloat = 20
  public static let densitySpace6Comfortable: CGFloat = 24
  public static let densityControlGapComfortable: CGFloat = 8
  public static let componentButtonGapComfortable: CGFloat = 8
  public static let componentButtonXsPaddingYComfortable: CGFloat = 4
  public static let componentButtonXsPaddingXComfortable: CGFloat = 10
  public static let componentButtonSmPaddingYComfortable: CGFloat = 8
  public static let componentButtonSmPaddingXComfortable: CGFloat = 14
  public static let componentButtonMdPaddingYComfortable: CGFloat = 12
  public static let componentButtonMdPaddingXComfortable: CGFloat = 20
  public static let componentButtonLgPaddingYComfortable: CGFloat = 16
  public static let componentButtonLgPaddingXComfortable: CGFloat = 28
  public static let componentTextfieldPaddingYComfortable: CGFloat = 10
  public static let componentTextfieldPaddingXComfortable: CGFloat = 12

  // Complete light elemental accent packs
  public static let accentThoSandLight = color(0xF8E9C0)
  public static let accentStrongThoSandLight = color(0x90825E)
  public static let accentBrightThoSandLight = color(0xF6EBCC)
  public static let accentOnThoSandLight = color(0x292414)
  public static let accentOnStrongThoSandLight = color(0x1A1108)
  public static let accentTintThoSandLight = color(0xFBF7EA)
  public static let accentInkThoSandLight = color(0x292414)
  public static let accentGlowThoSandLight = color(0xF8E9C0, alpha: 0.48)
  public static let accentGradAThoSandLight = color(0xF8E9C0)
  public static let accentGradBThoSandLight = color(0xF3B958)
  public static let colorTextAccentThoSandLight = color(0x90825E)
  public static let colorLinkThoSandLight = color(0x7B6D4A)
  public static let accentThoLight = color(0xF4BA17)
  public static let accentStrongThoLight = color(0xA47D17)
  public static let accentBrightThoLight = color(0xF4BA17)
  public static let accentOnThoLight = color(0x45210E)
  public static let accentOnStrongThoLight = color(0x1A1108)
  public static let accentTintThoLight = color(0xFBF4E9)
  public static let accentInkThoLight = color(0x45210E)
  public static let accentGlowThoLight = color(0xF4BA17, alpha: 0.48)
  public static let accentGradAThoLight = color(0xF4BA17)
  public static let accentGradBThoLight = color(0xF3B958)
  public static let accentThoClayLight = color(0x513801)
  public static let accentStrongThoClayLight = color(0x201300)
  public static let accentBrightThoClayLight = color(0xDEC7A2)
  public static let accentOnThoClayLight = color(0x2D220E)
  public static let accentOnStrongThoClayLight = color(0xFFFFFF)
  public static let accentTintThoClayLight = color(0xFFF6E7)
  public static let accentInkThoClayLight = color(0x2D220E)
  public static let accentGlowThoClayLight = color(0x513801, alpha: 0.48)
  public static let accentGradAThoClayLight = color(0x513801)
  public static let accentGradBThoClayLight = color(0xF3B958)
  public static let colorTextAccentThoClayLight = color(0x201300)
  public static let colorLinkThoClayLight = color(0x201300)
  public static let accentHoaPlasmaLight = color(0xFFE1D8)
  public static let accentStrongHoaPlasmaLight = color(0x967C75)
  public static let accentBrightHoaPlasmaLight = color(0xFCE6DF)
  public static let accentOnHoaPlasmaLight = color(0x2C211E)
  public static let accentOnStrongHoaPlasmaLight = color(0x1A1108)
  public static let accentTintHoaPlasmaLight = color(0xFEF4F2)
  public static let accentInkHoaPlasmaLight = color(0x2C211E)
  public static let accentGlowHoaPlasmaLight = color(0xFFE1D8, alpha: 0.48)
  public static let accentGradAHoaPlasmaLight = color(0xFFE1D8)
  public static let accentGradBHoaPlasmaLight = color(0xF4BA17)
  public static let colorTextAccentHoaPlasmaLight = color(0x967C75)
  public static let colorLinkHoaPlasmaLight = color(0x846B64)
  public static let accentHoaLight = color(0xFCAF91)
  public static let accentStrongHoaLight = color(0xB47054)
  public static let accentBrightHoaLight = color(0xFED3C3)
  public static let accentOnHoaLight = color(0x381B10)
  public static let accentOnStrongHoaLight = color(0x1A1108)
  public static let accentTintHoaLight = color(0xFFF4F0)
  public static let accentInkHoaLight = color(0x381B10)
  public static let accentGlowHoaLight = color(0xFCAF91, alpha: 0.48)
  public static let accentGradAHoaLight = color(0xFCAF91)
  public static let accentGradBHoaLight = color(0xF4BA17)
  public static let colorTextAccentHoaLight = color(0xB47054)
  public static let colorLinkHoaLight = color(0xA15E43)
  public static let accentHoaLavaLight = color(0x622B06)
  public static let accentStrongHoaLavaLight = color(0x280D00)
  public static let accentBrightHoaLavaLight = color(0xF1BEA4)
  public static let accentOnHoaLavaLight = color(0x361D0F)
  public static let accentOnStrongHoaLavaLight = color(0xFFFFFF)
  public static let accentTintHoaLavaLight = color(0xFFF4EF)
  public static let accentInkHoaLavaLight = color(0x361D0F)
  public static let accentGlowHoaLavaLight = color(0x622B06, alpha: 0.48)
  public static let accentGradAHoaLavaLight = color(0x622B06)
  public static let accentGradBHoaLavaLight = color(0xF4BA17)
  public static let colorTextAccentHoaLavaLight = color(0x280D00)
  public static let colorLinkHoaLavaLight = color(0x280D00)
  public static let accentThuyMistLight = color(0xC0F5FC)
  public static let accentStrongThuyMistLight = color(0x5A8A90)
  public static let accentBrightThuyMistLight = color(0xCDF4F9)
  public static let accentOnThuyMistLight = color(0x13282B)
  public static let accentOnStrongThuyMistLight = color(0x1A1108)
  public static let accentTintThuyMistLight = color(0xEBFAFC)
  public static let accentInkThuyMistLight = color(0x13282B)
  public static let accentGlowThuyMistLight = color(0xC0F5FC, alpha: 0.48)
  public static let accentGradAThuyMistLight = color(0xC0F5FC)
  public static let accentGradBThuyMistLight = color(0xA3D768)
  public static let colorTextAccentThuyMistLight = color(0x5A8A90)
  public static let colorLinkThuyMistLight = color(0x48787E)
  public static let accentThuyLight = color(0x2EDBF7)
  public static let accentStrongThuyLight = color(0x108EA0)
  public static let accentBrightThuyLight = color(0x99EEFF)
  public static let accentOnThuyLight = color(0x012A30)
  public static let accentOnStrongThuyLight = color(0x1A1108)
  public static let accentTintThuyLight = color(0xE7FBFF)
  public static let accentInkThuyLight = color(0x012A30)
  public static let accentGlowThuyLight = color(0x2EDBF7, alpha: 0.48)
  public static let accentGradAThuyLight = color(0x2EDBF7)
  public static let accentGradBThuyLight = color(0xA3D768)
  public static let colorTextAccentThuyLight = color(0x108EA0)
  public static let colorLinkThuyLight = color(0x027B8B)
  public static let accentThuyOceanLight = color(0x004554)
  public static let accentStrongThuyOceanLight = color(0x011A21)
  public static let accentBrightThuyOceanLight = color(0xA8D3E0)
  public static let accentOnThuyOceanLight = color(0x10282F)
  public static let accentOnStrongThuyOceanLight = color(0xFFFFFF)
  public static let accentTintThuyOceanLight = color(0xEAFAFF)
  public static let accentInkThuyOceanLight = color(0x10282F)
  public static let accentGlowThuyOceanLight = color(0x004554, alpha: 0.48)
  public static let accentGradAThuyOceanLight = color(0x004554)
  public static let accentGradBThuyOceanLight = color(0xA3D768)
  public static let colorTextAccentThuyOceanLight = color(0x011A21)
  public static let colorLinkThuyOceanLight = color(0x011A21)
  public static let accentMocBambooLight = color(0xE1F1C8)
  public static let accentStrongMocBambooLight = color(0x7C8965)
  public static let accentBrightMocBambooLight = color(0xE5F1D2)
  public static let accentOnMocBambooLight = color(0x212617)
  public static let accentOnStrongMocBambooLight = color(0x1A1108)
  public static let accentTintMocBambooLight = color(0xF4F9ED)
  public static let accentInkMocBambooLight = color(0x212617)
  public static let accentGlowMocBambooLight = color(0xE1F1C8, alpha: 0.48)
  public static let accentGradAMocBambooLight = color(0xE1F1C8)
  public static let accentGradBMocBambooLight = color(0xFCAF91)
  public static let colorTextAccentMocBambooLight = color(0x7C8965)
  public static let colorLinkMocBambooLight = color(0x687451)
  public static let accentMocLight = color(0xA3D768)
  public static let accentStrongMocLight = color(0x629122)
  public static let accentBrightMocLight = color(0xC5ED9C)
  public static let accentOnMocLight = color(0x182A00)
  public static let accentOnStrongMocLight = color(0x1A1108)
  public static let accentTintMocLight = color(0xEFFCE3)
  public static let accentInkMocLight = color(0x182A00)
  public static let accentGlowMocLight = color(0xA3D768, alpha: 0.48)
  public static let accentGradAMocLight = color(0xA3D768)
  public static let accentGradBMocLight = color(0xFCAF91)
  public static let colorTextAccentMocLight = color(0x629122)
  public static let colorLinkMocLight = color(0x517B13)
  public static let accentMocForestLight = color(0x1A4A01)
  public static let accentStrongMocForestLight = color(0x051D00)
  public static let accentBrightMocForestLight = color(0xB0D8A3)
  public static let accentOnMocForestLight = color(0x162A0E)
  public static let accentOnStrongMocForestLight = color(0xFFFFFF)
  public static let accentTintMocForestLight = color(0xECFDE7)
  public static let accentInkMocForestLight = color(0x162A0E)
  public static let accentGlowMocForestLight = color(0x1A4A01, alpha: 0.48)
  public static let accentGradAMocForestLight = color(0x1A4A01)
  public static let accentGradBMocForestLight = color(0xFCAF91)
  public static let colorTextAccentMocForestLight = color(0x051D00)
  public static let colorLinkMocForestLight = color(0x051D00)
  public static let accentKimTitaniumLight = color(0xFEE5C7)
  public static let accentStrongKimTitaniumLight = color(0x947F65)
  public static let accentBrightKimTitaniumLight = color(0xFBE8D2)
  public static let accentOnKimTitaniumLight = color(0x2B2217)
  public static let accentOnStrongKimTitaniumLight = color(0x1A1108)
  public static let accentTintKimTitaniumLight = color(0xFDF5ED)
  public static let accentInkKimTitaniumLight = color(0x2B2217)
  public static let accentGlowKimTitaniumLight = color(0xFEE5C7, alpha: 0.48)
  public static let accentGradAKimTitaniumLight = color(0xFEE5C7)
  public static let accentGradBKimTitaniumLight = color(0x2EDBF7)
  public static let colorTextAccentKimTitaniumLight = color(0x947F65)
  public static let colorLinkKimTitaniumLight = color(0x826D54)
  public static let accentKimLight = color(0xF3B958)
  public static let accentStrongKimLight = color(0xAC780B)
  public static let accentBrightKimLight = color(0xFDD89F)
  public static let accentOnKimLight = color(0x312002)
  public static let accentOnStrongKimLight = color(0x1A1108)
  public static let accentTintKimLight = color(0xFFF5E7)
  public static let accentInkKimLight = color(0x312002)
  public static let accentGlowKimLight = color(0xF3B958, alpha: 0.48)
  public static let accentGradAKimLight = color(0xF3B958)
  public static let accentGradBKimLight = color(0x2EDBF7)
  public static let colorTextAccentKimLight = color(0xAC780B)
  public static let colorLinkKimLight = color(0x966700)
  public static let accentKimSteelLight = color(0x503901)
  public static let accentStrongKimSteelLight = color(0x1F1400)
  public static let accentBrightKimSteelLight = color(0xDCC8A2)
  public static let accentOnKimSteelLight = color(0x2D220E)
  public static let accentOnStrongKimSteelLight = color(0xFFFFFF)
  public static let accentTintKimSteelLight = color(0xFEF6E7)
  public static let accentInkKimSteelLight = color(0x2D220E)
  public static let accentGlowKimSteelLight = color(0x503901, alpha: 0.48)
  public static let accentGradAKimSteelLight = color(0x503901)
  public static let accentGradBKimSteelLight = color(0x2EDBF7)
  public static let colorTextAccentKimSteelLight = color(0x1F1400)
  public static let colorLinkKimSteelLight = color(0x1F1400)

  // MARK: dark elemental accent packs (APCA-derived, v4.0.0)
  public static let accentThoSandDark = color(0xF8E9C0)
  public static let accentStrongThoSandDark = color(0x665A37)
  public static let accentBrightThoSandDark = color(0xF6EBCC)
  public static let accentOnThoSandDark = color(0xF5EAD9)
  public static let accentOnStrongThoSandDark = color(0xFFFDF8)
  public static let accentTintThoSandDark = color(0x332701)
  public static let accentInkThoSandDark = color(0xF6EBCC)
  public static let accentGlowThoSandDark = color(0xF8E9C0, alpha: 0.48)
  public static let accentGradAThoSandDark = color(0xF8E9C0)
  public static let accentGradBThoSandDark = color(0xF3B958)
  public static let colorTextAccentThoSandDark = color(0xF6EBCC)
  public static let colorLinkThoSandDark = color(0xF6EBCC)
  public static let accentThoDark = color(0xF4BA17)
  public static let accentStrongThoDark = color(0x73560B)
  public static let accentBrightThoDark = color(0xFEC42C)
  public static let accentOnThoDark = color(0xF5EAD9)
  public static let accentOnStrongThoDark = color(0xFFFDF8)
  public static let accentTintThoDark = color(0x352602)
  public static let accentInkThoDark = color(0xFECD5E)
  public static let accentGlowThoDark = color(0xF4BA17, alpha: 0.48)
  public static let accentGradAThoDark = color(0xF4BA17)
  public static let accentGradBThoDark = color(0xF3B958)
  public static let accentThoClayDark = color(0xCDB07E)
  public static let accentStrongThoClayDark = color(0x1F1300)
  public static let accentBrightThoClayDark = color(0xE4CDA8)
  public static let accentOnThoClayDark = color(0xF5EAD9)
  public static let accentOnStrongThoClayDark = color(0xFFFDF8)
  public static let accentTintThoClayDark = color(0x372502)
  public static let accentInkThoClayDark = color(0xE7D0AB)
  public static let accentGlowThoClayDark = color(0x513801, alpha: 0.48)
  public static let accentGradAThoClayDark = color(0x513801)
  public static let accentGradBThoClayDark = color(0xF3B958)
  public static let colorTextAccentThoClayDark = color(0xE4CDA8)
  public static let colorLinkThoClayDark = color(0xE4CDA8)
  public static let accentHoaPlasmaDark = color(0xFFE1D8)
  public static let accentStrongHoaPlasmaDark = color(0x6F5750)
  public static let accentBrightHoaPlasmaDark = color(0xFCE6DF)
  public static let accentOnHoaPlasmaDark = color(0xF5EAD9)
  public static let accentOnStrongHoaPlasmaDark = color(0xFFFDF8)
  public static let accentTintHoaPlasmaDark = color(0x38231C)
  public static let accentInkHoaPlasmaDark = color(0xFCE6DF)
  public static let accentGlowHoaPlasmaDark = color(0xFFE1D8, alpha: 0.48)
  public static let accentGradAHoaPlasmaDark = color(0xFFE1D8)
  public static let accentGradBHoaPlasmaDark = color(0xF4BA17)
  public static let colorTextAccentHoaPlasmaDark = color(0xFCE6DF)
  public static let colorLinkHoaPlasmaDark = color(0xFCE6DF)
  public static let accentHoaDark = color(0xFCAF91)
  public static let accentStrongHoaDark = color(0x8A4A30)
  public static let accentBrightHoaDark = color(0xFED3C3)
  public static let accentOnHoaDark = color(0xF5EAD9)
  public static let accentOnStrongHoaDark = color(0xFFFDF8)
  public static let accentTintHoaDark = color(0x411E0F)
  public static let accentInkHoaDark = color(0xFED3C3)
  public static let accentGlowHoaDark = color(0xFCAF91, alpha: 0.48)
  public static let accentGradAHoaDark = color(0xFCAF91)
  public static let accentGradBHoaDark = color(0xF4BA17)
  public static let colorTextAccentHoaDark = color(0xFED3C3)
  public static let colorLinkHoaDark = color(0xFED3C3)
  public static let accentHoaLavaDark = color(0xE8A683)
  public static let accentStrongHoaLavaDark = color(0x280D00)
  public static let accentBrightHoaLavaDark = color(0xF8C4AA)
  public static let accentOnHoaLavaDark = color(0xF5EAD9)
  public static let accentOnStrongHoaLavaDark = color(0xFFFDF8)
  public static let accentTintHoaLavaDark = color(0x401F0B)
  public static let accentInkHoaLavaDark = color(0xFBC7AD)
  public static let accentGlowHoaLavaDark = color(0x622B06, alpha: 0.48)
  public static let accentGradAHoaLavaDark = color(0x622B06)
  public static let accentGradBHoaLavaDark = color(0xF4BA17)
  public static let colorTextAccentHoaLavaDark = color(0xF8C4AA)
  public static let colorLinkHoaLavaDark = color(0xF8C4AA)
  public static let accentThuyMistDark = color(0xC0F5FC)
  public static let accentStrongThuyMistDark = color(0x316167)
  public static let accentBrightThuyMistDark = color(0xCDF4F9)
  public static let accentOnThuyMistDark = color(0xF5EAD9)
  public static let accentOnStrongThuyMistDark = color(0xFFFDF8)
  public static let accentTintThuyMistDark = color(0x022F34)
  public static let accentInkThuyMistDark = color(0xCDF4F9)
  public static let accentGlowThuyMistDark = color(0xC0F5FC, alpha: 0.48)
  public static let accentGradAThuyMistDark = color(0xC0F5FC)
  public static let accentGradBThuyMistDark = color(0xA3D768)
  public static let colorTextAccentThuyMistDark = color(0xCDF4F9)
  public static let colorLinkThuyMistDark = color(0xCDF4F9)
  public static let accentThuyDark = color(0x2EDBF7)
  public static let accentStrongThuyDark = color(0x046270)
  public static let accentBrightThuyDark = color(0x99EEFF)
  public static let accentOnThuyDark = color(0xF5EAD9)
  public static let accentOnStrongThuyDark = color(0xFFFDF8)
  public static let accentTintThuyDark = color(0x032F36)
  public static let accentInkThuyDark = color(0x99EEFF)
  public static let accentGlowThuyDark = color(0x2EDBF7, alpha: 0.48)
  public static let accentGradAThuyDark = color(0x2EDBF7)
  public static let accentGradBThuyDark = color(0xA3D768)
  public static let colorTextAccentThuyDark = color(0x99EEFF)
  public static let colorLinkThuyDark = color(0x99EEFF)
  public static let accentThuyOceanDark = color(0x82BCCD)
  public static let accentStrongThuyOceanDark = color(0x011A21)
  public static let accentBrightThuyOceanDark = color(0xABD6E3)
  public static let accentOnThuyOceanDark = color(0xF5EAD9)
  public static let accentOnStrongThuyOceanDark = color(0xFFFDF8)
  public static let accentTintThuyOceanDark = color(0x002F3A)
  public static let accentInkThuyOceanDark = color(0xAED9E6)
  public static let accentGlowThuyOceanDark = color(0x004554, alpha: 0.48)
  public static let accentGradAThuyOceanDark = color(0x004554)
  public static let accentGradBThuyOceanDark = color(0xA3D768)
  public static let colorTextAccentThuyOceanDark = color(0xABD6E3)
  public static let colorLinkThuyOceanDark = color(0xABD6E3)
  public static let accentMocBambooDark = color(0xE1F1C8)
  public static let accentStrongMocBambooDark = color(0x54603E)
  public static let accentBrightMocBambooDark = color(0xE5F1D2)
  public static let accentOnMocBambooDark = color(0xF5EAD9)
  public static let accentOnStrongMocBambooDark = color(0xFFFDF8)
  public static let accentTintMocBambooDark = color(0x232D0B)
  public static let accentInkMocBambooDark = color(0xE5F1D2)
  public static let accentGlowMocBambooDark = color(0xE1F1C8, alpha: 0.48)
  public static let accentGradAMocBambooDark = color(0xE1F1C8)
  public static let accentGradBMocBambooDark = color(0xFCAF91)
  public static let colorTextAccentMocBambooDark = color(0xE5F1D2)
  public static let colorLinkMocBambooDark = color(0xE5F1D2)
  public static let accentMocDark = color(0xA3D768)
  public static let accentStrongMocDark = color(0x416501)
  public static let accentBrightMocDark = color(0xC5ED9C)
  public static let accentOnMocDark = color(0xF5EAD9)
  public static let accentOnStrongMocDark = color(0xFFFDF8)
  public static let accentTintMocDark = color(0x1F2E0B)
  public static let accentInkMocDark = color(0xC5ED9C)
  public static let accentGlowMocDark = color(0xA3D768, alpha: 0.48)
  public static let accentGradAMocDark = color(0xA3D768)
  public static let accentGradBMocDark = color(0xFCAF91)
  public static let colorTextAccentMocDark = color(0xC5ED9C)
  public static let colorLinkMocDark = color(0xC5ED9C)
  public static let accentMocForestDark = color(0x8EC27D)
  public static let accentStrongMocForestDark = color(0x061D00)
  public static let accentBrightMocForestDark = color(0xB0D8A3)
  public static let accentOnMocForestDark = color(0xF5EAD9)
  public static let accentOnStrongMocForestDark = color(0xFFFDF8)
  public static let accentTintMocForestDark = color(0x193011)
  public static let accentInkMocForestDark = color(0xB6DFA9)
  public static let accentGlowMocForestDark = color(0x1A4A01, alpha: 0.48)
  public static let accentGradAMocForestDark = color(0x1A4A01)
  public static let accentGradBMocForestDark = color(0xFCAF91)
  public static let colorTextAccentMocForestDark = color(0xB0D8A3)
  public static let colorLinkMocForestDark = color(0xB0D8A3)
  public static let accentKimTitaniumDark = color(0xFEE5C7)
  public static let accentStrongKimTitaniumDark = color(0x6B573E)
  public static let accentBrightKimTitaniumDark = color(0xFBE8D2)
  public static let accentOnKimTitaniumDark = color(0xF5EAD9)
  public static let accentOnStrongKimTitaniumDark = color(0xFFFDF8)
  public static let accentTintKimTitaniumDark = color(0x37250B)
  public static let accentInkKimTitaniumDark = color(0xFBE8D2)
  public static let accentGlowKimTitaniumDark = color(0xFEE5C7, alpha: 0.48)
  public static let accentGradAKimTitaniumDark = color(0xFEE5C7)
  public static let accentGradBKimTitaniumDark = color(0x2EDBF7)
  public static let colorTextAccentKimTitaniumDark = color(0xFBE8D2)
  public static let colorLinkKimTitaniumDark = color(0xFBE8D2)
  public static let accentKimDark = color(0xF3B958)
  public static let accentStrongKimDark = color(0x795303)
  public static let accentBrightKimDark = color(0xFDD89F)
  public static let accentOnKimDark = color(0xF5EAD9)
  public static let accentOnStrongKimDark = color(0xFFFDF8)
  public static let accentTintKimDark = color(0x382503)
  public static let accentInkKimDark = color(0xFDD89F)
  public static let accentGlowKimDark = color(0xF3B958, alpha: 0.48)
  public static let accentGradAKimDark = color(0xF3B958)
  public static let accentGradBKimDark = color(0x2EDBF7)
  public static let colorTextAccentKimDark = color(0xFDD89F)
  public static let colorLinkKimDark = color(0xFDD89F)
  public static let accentKimSteelDark = color(0xCCB17E)
  public static let accentStrongKimSteelDark = color(0x1F1400)
  public static let accentBrightKimSteelDark = color(0xDFCBA5)
  public static let accentOnKimSteelDark = color(0xF5EAD9)
  public static let accentOnStrongKimSteelDark = color(0xFFFDF8)
  public static let accentTintKimSteelDark = color(0x362602)
  public static let accentInkKimSteelDark = color(0xE6D1AB)
  public static let accentGlowKimSteelDark = color(0x503901, alpha: 0.48)
  public static let accentGradAKimSteelDark = color(0x503901)
  public static let accentGradBKimSteelDark = color(0x2EDBF7)
  public static let colorTextAccentKimSteelDark = color(0xDFCBA5)
  public static let colorLinkKimSteelDark = color(0xDFCBA5)
}
