import { createElement, useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import {
  AIDisclosureBadge,
  Badge,
  Button,
  ChatMessage,
  CitationList,
  ConfidenceMeter,
  LumiAvatar,
  NavItem,
  PromptInput,
  PromptSuggestions,
  Sidebar,
  TypingIndicator,
} from "@cyberskill/react";

function LumiPage() {
  const [msgs, setMsgs] = useState([{ who: "lumi", kind: "intro" }]);
  const [typing, setTyping] = useState(false);
  const threadRef = useRef(null);
  useEffect(() => {
    const t = threadRef.current;
    if (t) t.scrollTop = t.scrollHeight;
  }, [msgs, typing]);

  function ask(text) {
    const m = (text || "").trim();
    if (!m) return;
    setMsgs((c) => [...c, { who: "user", text: m }]);
    setTyping(true);
    setTimeout(() => {
      setTyping(false);
      setMsgs((c) => [...c, { who: "lumi", kind: "answer", text: m }]);
    }, 1100);
  }

  return (
    <div className="lumi-page">
      <aside className="lumi-side">
        <div className="lumi-brand"><img src="../../assets/logo-mark.svg" alt="" />CyberSkill</div>
        <div className="lumi-new">
          <Button variant="primary" size="sm" fullWidth onClick={() => setMsgs([{ who: "lumi", kind: "intro" }])}>✦ New wish</Button>
        </div>
        <div className="lumi-conv-label">Recent</div>
        <Sidebar>
          <NavItem active>A faster checkout</NavItem>
          <NavItem>Internal ops console</NavItem>
          <NavItem>Bilingual design system</NavItem>
        </Sidebar>
        <div className="lumi-side-foot">
          <NavItem icon={<LumiAvatar size="sm" />}>Lumi · genie mode</NavItem>
        </div>
      </aside>

      <main id="main" className="lumi-main">
        <header className="lumi-top">
          <LumiAvatar src="../../assets/lumi-poster.webp" size="md" ring />
          <div><h1>Lumi</h1><div className="sub">Golden genie · replies, then hands clear wishes to a human</div></div>
          <span style={{ marginLeft: "auto" }}><Badge variant="info">AI-native</Badge></span>
        </header>

        <div className="lumi-thread" ref={threadRef}>
          <div className="lumi-thread-inner">
            {msgs.map((m, i) => {
              if (m.who === "user") return <ChatMessage key={i} role="user">{m.text}</ChatMessage>;
              if (m.kind === "intro") {
                return (
                  <div key={i}>
                    <ChatMessage role="lumi" avatar={<LumiAvatar size="sm" />}>
                      Hello, I’m Lumi. Tell me a wish, and I’ll share plain advice before asking for anything. When a wish is clear, it goes to a real person on the team.
                    </ChatMessage>
                    <div style={{ marginTop: 12, marginLeft: 42 }}>
                      <PromptSuggestions suggestions={["A web app", "An internal tool", "A design system"]} onSelect={ask} />
                    </div>
                  </div>
                );
              }
              return (
                <ChatMessage key={i} role="lumi" avatar={<LumiAvatar size="sm" />}>
                  <div className="lumi-answer-card">
                    <p>A wish worth granting. For “{m.text}”, I’d start with a two-week shaping sprint — scope, a clickable prototype, and an honest estimate. Shall I hand this to the team?</p>
                    <div className="lumi-answer-meta">
                      <ConfidenceMeter value={0.82} label="Confidence" />
                      <AIDisclosureBadge label="AI assisted" details="Draft plan generated by Lumi from your wish, reviewed before handoff." sources={["Services", "Process"]} />
                    </div>
                    <CitationList label="Grounded in" items={[{ title: "What we build", source: "Services" }, { title: "The arc of a wish", source: "Process" }]} />
                    <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
                      <Button size="sm">Hand to the team</Button>
                      <Button variant="secondary" size="sm">Keep refining</Button>
                    </div>
                  </div>
                </ChatMessage>
              );
            })}
            {typing && <ChatMessage role="lumi" avatar={<LumiAvatar size="sm" />}><TypingIndicator /></ChatMessage>}
          </div>
        </div>

        <div className="lumi-compose">
          <div className="lumi-compose-inner">
            <PromptInput onSubmit={ask} placeholder="Make a wish…" sendLabel="Send" />
          </div>
        </div>
      </main>
    </div>
  );
}

createRoot(document.getElementById("root")).render(createElement(LumiPage));
